PotteryOven Kiln Controller: Core/Inc/encoder.h File Reference
encoder.h File Reference
Rotary encoder driver with interrupt-based rotation detection.
#include "main.h"
#include "stm32f0xx_hal.h"
#include "ui.h"
#include "event.h"
Data Structures
struct Encoder_HandleTypeDef_t
Handle structure for the rotary encoder.
Functions
HAL_StatusTypeDef init_Encoder (Encoder_HandleTypeDef_t *hencoder, Event_Queue_HandleTypeDef_t *queue, GPIO_TypeDef *port_a, uint16_t pin_a, GPIO_TypeDef *port_b, uint16_t pin_b, GPIO_TypeDef *port_button, uint16_t pin_button)
Initialize the encoder driver.
void encoder_callback (Encoder_HandleTypeDef_t *hencoder, uint16_t pin)
Process encoder interrupt callback.
HAL_StatusTypeDef encoder_get_state (Encoder_HandleTypeDef_t *hencoder, uint8_t *position, uint8_t *direction)
Get both position and direction of the encoder.
HAL_StatusTypeDef encoder_get_position (Encoder_HandleTypeDef_t *hencoder, uint8_t *position)
Get current encoder position.
HAL_StatusTypeDef encoder_get_direction (Encoder_HandleTypeDef_t *hencoder, uint8_t *direction)
Get last rotation direction.
Detailed Description
Rotary encoder driver with interrupt-based rotation detection.
Author
Dennis Rathgeb
Date
Apr 8, 2024
Driver for rotary encoder with integrated push button. The button and output A of the encoder are connected to GPIO interrupts. In the interrupt callback, encoder_callback() is called with the pin that triggered the interrupt so the encoder can update its state.
When the button is pressed, position and direction are reset to zero.
Note
Uses TIM3 input capture for encoder rotation detection.
Definition in file encoder.h.
Function Documentation
encoder_callback()
void encoder_callback (Encoder_HandleTypeDef_t * hencoder, uint16_t pin)
Process encoder interrupt callback.
Parameters
[in,out] hencoder Pointer to encoder handle
[in] pin GPIO pin that triggered the interrupt (0xff for rotation, button pin for button)
Call this function from HAL_GPIO_EXTI_Callback() or HAL_TIM_IC_CaptureCallback(). For rotation events, pass 0xff as the pin parameter. For button press, pass the button pin value.
Parameters
[in,out] hencoder Pointer to encoder handle
[in] pin GPIO pin that triggered the interrupt
Called from interrupt context to update encoder state.
If pin is 0xff: reads A and B pins to determine rotation direction
If pin matches button pin: posts ENC_BUT event and resets position
Direction is determined by comparing A and B states:
Same state = clockwise (direction 0)
Different state = counter-clockwise (direction 1)
Definition at line 68 of file encoder.c.
References ENC_BUT, event_enqueue(), hencoder, and update_position().
Referenced by HAL_GPIO_EXTI_Callback(), and HAL_TIM_IC_CaptureCallback().
encoder_get_direction()
HAL_StatusTypeDef encoder_get_direction (Encoder_HandleTypeDef_t * hencoder, uint8_t * direction)
Get last rotation direction.
Parameters
[in] hencoder Pointer to encoder handle
[out] direction Pointer to store direction (1=clockwise, 0=counter-clockwise)
Returns
HAL_OK on success, HAL_ERROR if handle is NULL
Definition at line 161 of file encoder.c.
References hencoder.
Referenced by encoder_get_state().
encoder_get_position()
HAL_StatusTypeDef encoder_get_position (Encoder_HandleTypeDef_t * hencoder, uint8_t * position)
Get current encoder position.
Parameters
[in] hencoder Pointer to encoder handle
[out] position Pointer to store current position
Returns
HAL_OK on success, HAL_ERROR if handle is NULL
Note
Position is truncated to uint8_t, may lose information for large values
Parameters
[in] hencoder Pointer to encoder handle
[out] position Pointer to store current position (truncated to uint8_t)
Returns
HAL_OK on success, HAL_ERROR if handle is NULL
Warning
Position is cast to uint8_t, values outside 0-255 will be truncated
Definition at line 143 of file encoder.c.
References hencoder.
Referenced by encoder_get_state().
encoder_get_state()
HAL_StatusTypeDef encoder_get_state (Encoder_HandleTypeDef_t * hencoder, uint8_t * position, uint8_t * direction)
Get both position and direction of the encoder.
Parameters
[in] hencoder Pointer to encoder handle
[out] position Pointer to store current position
[out] direction Pointer to store last direction (1=CW, 0=CCW)
Returns
HAL_OK on success, HAL_ERROR if handle is NULL
Parameters
[in] hencoder Pointer to encoder handle
[out] position Pointer to store current position
[out] direction Pointer to store last direction (1=CW, 0=CCW)
Returns
HAL_OK on success, HAL_ERROR if any getter fails
Convenience function that calls both encoder_get_position and encoder_get_direction.
Definition at line 120 of file encoder.c.
References encoder_get_direction(), encoder_get_position(), and hencoder.
init_Encoder()
HAL_StatusTypeDef init_Encoder (Encoder_HandleTypeDef_t * hencoder, Event_Queue_HandleTypeDef_t * queue, GPIO_TypeDef * port_a, uint16_t pin_a, GPIO_TypeDef * port_b, uint16_t pin_b, GPIO_TypeDef * port_button, uint16_t pin_button)
Initialize the encoder driver.
Parameters
[out] hencoder Pointer to encoder handle to initialize
[in] queue Pointer to event queue for posting events
[in] port_a GPIO port for encoder output A
[in] pin_a GPIO pin for encoder output A
[in] port_b GPIO port for encoder output B
[in] pin_b GPIO pin for encoder output B
[in] port_button GPIO port for encoder button
[in] pin_button GPIO pin for encoder button
Returns
HAL_OK on success
Parameters
[out] hencoder Pointer to encoder handle to initialize
[in] queue Pointer to event queue for posting events
[in] port_a GPIO port for encoder output A
[in] pin_a GPIO pin for encoder output A
[in] port_b GPIO port for encoder output B
[in] pin_b GPIO pin for encoder output B
[in] port_button GPIO port for encoder button
[in] pin_button GPIO pin for encoder button
Returns
HAL_OK on success
Stores GPIO configuration and initializes position/direction to zero.
Definition at line 36 of file encoder.c.
References hencoder.
Referenced by main().