PotteryOven Kiln Controller: Core/Inc/event.h File Reference
event.h File Reference
Event queue module for decoupling interrupt handlers from UI processing.
#include "stm32f0xx_hal.h"
#include "log.h"
#include <stdio.h>
#include <stdlib.h>
Data Structures
struct event_node_t
Node structure for the event queue linked list.
struct Event_Queue_HandleTypeDef_t
Handle structure for the event queue.
Typedefs
typedef struct event_node_t event_node_t
Node structure for the event queue linked list.
Enumerations
enum event_type_t {
NO_EVENT = 0 , BUT1 = 1 , BUT2 = 2 , BUT3 = 3 ,
BUT4 = 4 , ENC_BUT = 5 , ENC_UP = 6 , ENC_DOWN = 7
}
Enable debug output to UART for event module.
Functions
HAL_StatusTypeDef initEvent (Event_Queue_HandleTypeDef_t *queue)
Initialize the event queue.
uint8_t event_isEmpty (Event_Queue_HandleTypeDef_t *queue)
Check if the event queue is empty.
event_node_t * event_createNode (event_type_t data)
Create a new event node.
void event_enqueue (Event_Queue_HandleTypeDef_t *queue, event_type_t event)
Add an event to the queue.
event_type_t event_dequeue (Event_Queue_HandleTypeDef_t *queue)
Remove and return the next event from the queue.
void event_displayQueue (Event_Queue_HandleTypeDef_t *queue)
Display the contents of the queue (debug function).
Detailed Description
Event queue module for decoupling interrupt handlers from UI processing.
Author
Dennis Rathgeb
Date
Apr 26, 2024
This module implements a linked-list FIFO queue for events generated by button presses and encoder rotation. Events are enqueued in ISR context and dequeued in the main loop for UI processing.
Note
Uses dynamic memory allocation (malloc/free) which may not be ideal for real-time embedded systems. Consider using a static memory pool.
Definition in file event.h.
Typedef Documentation
event_node_t
typedef struct event_node_t event_node_t
Node structure for the event queue linked list.
Enumeration Type Documentation
event_type_t
enum event_type_t
Enable debug output to UART for event module.
Enumeration of all possible event types
Events are generated by button presses and encoder rotation.
Enumerator
NO_EVENT
No event pending
BUT1
Button 1 pressed (navigate left/down)
BUT2
Button 2 pressed (navigate right/up)
BUT3
Button 3 pressed (navigate back)
BUT4
Button 4 pressed (start/stop)
ENC_BUT
Encoder button pressed (enter/select)
ENC_UP
Encoder rotated clockwise (up/right)
ENC_DOWN
Encoder rotated counter-clockwise (down/left)
Definition at line 31 of file event.h.
Function Documentation
event_createNode()
event_node_t * event_createNode (event_type_t data)
Create a new event node.
Parameters
[in] data Event type to store in the node
Returns
Pointer to newly allocated node
Warning
Calls exit() on malloc failure - not recommended for embedded systems
Create a new event node.
Parameters
[in] data Event type to store in the node
Returns
Pointer to newly allocated and initialized node
Warning
Calls exit(EXIT_FAILURE) on malloc failure - inappropriate for embedded systems
Definition at line 85 of file event.c.
References event_node_t::data, and event_node_t::next.
Referenced by event_enqueue().
event_dequeue()
event_type_t event_dequeue (Event_Queue_HandleTypeDef_t * queue)
Remove and return the next event from the queue.
Parameters
[in,out] queue Pointer to queue handle
Returns
The event type at the front of the queue
Warning
Calls exit() if queue is empty - check with event_isEmpty() first
Remove and return the next event from the queue.
Parameters
[in,out] queue Pointer to queue handle
Returns
The event type that was at the front of the queue
Warning
Calls exit(EXIT_FAILURE) if queue is empty - check isEmpty() first
Removes the front node, frees its memory, and returns the stored event. Updates rear to NULL if queue becomes empty after dequeue.
Definition at line 125 of file event.c.
References event_node_t::data, event_isEmpty(), Event_Queue_HandleTypeDef_t::front, event_node_t::next, and Event_Queue_HandleTypeDef_t::rear.
Referenced by ui_get_events().
event_displayQueue()
void event_displayQueue (Event_Queue_HandleTypeDef_t * queue)
Display the contents of the queue (debug function).
Parameters
[in] queue Pointer to queue handle
Prints all events in the queue to stdout.
Display the contents of the queue (debug function).
Parameters
[in] queue Pointer to queue handle
Iterates through the queue and prints each event's numeric value. Does not modify the queue.
Definition at line 147 of file event.c.
References event_node_t::data, Event_Queue_HandleTypeDef_t::front, and event_node_t::next.
event_enqueue()
void event_enqueue (Event_Queue_HandleTypeDef_t * queue, event_type_t event)
Add an event to the queue.
Parameters
[in,out] queue Pointer to queue handle
[in] event Event type to enqueue
This function is typically called from ISR context when a button is pressed or the encoder is rotated.
Add an event to the queue.
Parameters
[in,out] queue Pointer to queue handle
[in] event Event type to enqueue
Creates a new node and adds it to the rear of the queue. If queue is empty, the new node becomes both front and rear. Logs the event type if EVENT_ENABLE_LOG is defined.
Definition at line 105 of file event.c.
References event_createNode(), event_diplay_type(), event_isEmpty(), Event_Queue_HandleTypeDef_t::front, event_node_t::next, and Event_Queue_HandleTypeDef_t::rear.
Referenced by encoder_callback(), HAL_GPIO_EXTI_Callback(), and update_position().
event_isEmpty()
uint8_t event_isEmpty (Event_Queue_HandleTypeDef_t * queue)
Check if the event queue is empty.
Parameters
[in] queue Pointer to queue handle
Returns
1 if queue is empty, 0 if queue has events
Parameters
[in] queue Pointer to queue handle
Returns
1 if queue is empty (front is NULL), 0 otherwise
Definition at line 75 of file event.c.
References Event_Queue_HandleTypeDef_t::front.
Referenced by event_dequeue(), event_enqueue(), and ui_get_events().
initEvent()
HAL_StatusTypeDef initEvent (Event_Queue_HandleTypeDef_t * queue)
Initialize the event queue.
Parameters
[in,out] queue Pointer to queue handle to initialize
Returns
HAL_OK on success, HAL_ERROR if queue is NULL
Parameters
[in,out] queue Pointer to queue handle to initialize
Returns
HAL_OK on success, HAL_ERROR if queue is NULL
Sets front and rear pointers to NULL, indicating an empty queue.
< Error level - error conditions
Definition at line 59 of file event.c.
References Event_Queue_HandleTypeDef_t::front, LOG_ERROR, logMsg(), and Event_Queue_HandleTypeDef_t::rear.
Referenced by main().