PotteryOven Kiln Controller: Core/Src/event.c File Reference
event.c File Reference
Implementation of event queue for UI event handling.
#include <event.h>
#include <stdio.h>
#include <stdlib.h>
Functions
static void event_diplay_type (event_type_t event)
Log event type to terminal when event callback is triggered.
HAL_StatusTypeDef initEvent (Event_Queue_HandleTypeDef_t *queue)
Initialize the event queue.
uint8_t event_isEmpty (Event_Queue_HandleTypeDef_t *queue)
Check if the event queue is empty.
event_node_t * event_createNode (event_type_t data)
Create a new event node with dynamic memory allocation.
void event_enqueue (Event_Queue_HandleTypeDef_t *queue, event_type_t event)
Add an event to the rear of the queue.
event_type_t event_dequeue (Event_Queue_HandleTypeDef_t *queue)
Remove and return the event at the front of the queue.
void event_displayQueue (Event_Queue_HandleTypeDef_t *queue)
Display all events in the queue (debug function).
Detailed Description
Implementation of event queue for UI event handling.
Author
Dennis Rathgeb
Date
Apr 26, 2024
Implements a linked-list FIFO queue for decoupling interrupt handlers from UI processing. Events from buttons and encoder are queued here.
Definition in file event.c.
Function Documentation
event_createNode()
event_node_t * event_createNode (event_type_t data)
Create a new event node with dynamic memory allocation.
Create a new event node.
Parameters
[in] data Event type to store in the node
Returns
Pointer to newly allocated and initialized node
Warning
Calls exit(EXIT_FAILURE) on malloc failure - inappropriate for embedded systems
Definition at line 85 of file event.c.
References event_node_t::data, and event_node_t::next.
Referenced by event_enqueue().
event_dequeue()
event_type_t event_dequeue (Event_Queue_HandleTypeDef_t * queue)
Remove and return the event at the front of the queue.
Remove and return the next event from the queue.
Parameters
[in,out] queue Pointer to queue handle
Returns
The event type that was at the front of the queue
Warning
Calls exit(EXIT_FAILURE) if queue is empty - check isEmpty() first
Removes the front node, frees its memory, and returns the stored event. Updates rear to NULL if queue becomes empty after dequeue.
Definition at line 125 of file event.c.
References event_node_t::data, event_isEmpty(), Event_Queue_HandleTypeDef_t::front, event_node_t::next, and Event_Queue_HandleTypeDef_t::rear.
Referenced by ui_get_events().
event_diplay_type()
void event_diplay_type (event_type_t event) static
Log event type to terminal when event callback is triggered.
Parameters
[in] event Event type to display
Only outputs if EVENT_ENABLE_LOG is defined.
< Info level - general information messages
< Info level - general information messages
< Info level - general information messages
< Info level - general information messages
< Info level - general information messages
< Info level - general information messages
< Info level - general information messages
< Warning level - potential issues
Definition at line 21 of file event.c.
References BUT1, BUT2, BUT3, BUT4, ENC_BUT, ENC_DOWN, ENC_UP, LOG_INFO, LOG_WARNING, and logMsg().
Referenced by event_enqueue().
event_displayQueue()
void event_displayQueue (Event_Queue_HandleTypeDef_t * queue)
Display all events in the queue (debug function).
Display the contents of the queue (debug function).
Parameters
[in] queue Pointer to queue handle
Iterates through the queue and prints each event's numeric value. Does not modify the queue.
Definition at line 147 of file event.c.
References event_node_t::data, Event_Queue_HandleTypeDef_t::front, and event_node_t::next.
event_enqueue()
void event_enqueue (Event_Queue_HandleTypeDef_t * queue, event_type_t event)
Add an event to the rear of the queue.
Add an event to the queue.
Parameters
[in,out] queue Pointer to queue handle
[in] event Event type to enqueue
Creates a new node and adds it to the rear of the queue. If queue is empty, the new node becomes both front and rear. Logs the event type if EVENT_ENABLE_LOG is defined.
Definition at line 105 of file event.c.
References event_createNode(), event_diplay_type(), event_isEmpty(), Event_Queue_HandleTypeDef_t::front, event_node_t::next, and Event_Queue_HandleTypeDef_t::rear.
Referenced by encoder_callback(), HAL_GPIO_EXTI_Callback(), and update_position().
event_isEmpty()
uint8_t event_isEmpty (Event_Queue_HandleTypeDef_t * queue)
Check if the event queue is empty.
Parameters
[in] queue Pointer to queue handle
Returns
1 if queue is empty (front is NULL), 0 otherwise
Definition at line 75 of file event.c.
References Event_Queue_HandleTypeDef_t::front.
Referenced by event_dequeue(), event_enqueue(), and ui_get_events().
initEvent()
HAL_StatusTypeDef initEvent (Event_Queue_HandleTypeDef_t * queue)
Initialize the event queue.
Parameters
[in,out] queue Pointer to queue handle to initialize
Returns
HAL_OK on success, HAL_ERROR if queue is NULL
Sets front and rear pointers to NULL, indicating an empty queue.
< Error level - error conditions
Definition at line 59 of file event.c.
References Event_Queue_HandleTypeDef_t::front, LOG_ERROR, logMsg(), and Event_Queue_HandleTypeDef_t::rear.
Referenced by main().