PotteryOven Kiln Controller: Core/Inc/heater.h File Reference
heater.h File Reference
Heater control module for kiln heating coils.
#include <stdio.h>
#include "main.h"
#include "log.h"
#include "stm32f0xx_hal.h"
#include "arm_math.h"
#include "MAX31855.h"
Data Structures
struct heater_coil_t
Structure for individual heating coil.
struct heater_coils_t
Structure containing all three heating coils.
struct Heater_HandleTypeDef_t
Handle structure for heater control.
Macros
#define PWM_ON_SECONDS 2
PWM toggle period in seconds (coil stays on for this duration).
#define INTERUPT_INTERVAL_SECONDS 1
RTC alarm interval in seconds (must be <= other intervals).
#define TEMPERATURE_SAMPLING_INTERVAL_SECONDS 1
Temperature sampling interval in seconds.
#define PID_CALC_INTERVAL_SECONDS 10
PID calculation interval in seconds.
#define HEATER_ENABLE_LOG
Enable printf logs for heater module.
#define MAX_MEAS_AR_LENGTH 20
Maximum length for temperature measurement arrays.
Enumerations
enum heater_coil_state_t { COIL_OFF = 0 , COIL_ON = 1 , COIL_PWM = 2 }
States that a heating coil can have.
Functions
HAL_StatusTypeDef initHeater (Heater_HandleTypeDef_t *hheater, MAX31855_HandleTypeDef_t *htemp, GPIO_TypeDef *coil1_port, uint16_t coil1_pin, GPIO_TypeDef *coil2_port, uint16_t coil2_pin, GPIO_TypeDef *coil3_port, uint16_t coil3_pin)
Initialize the heater module.
HAL_StatusTypeDef heater_set_level (Heater_HandleTypeDef_t *hheater, uint8_t level)
Set the heater power level.
HAL_StatusTypeDef heater_set_state (Heater_HandleTypeDef_t *hheater)
Apply the configured heater state to GPIO outputs.
HAL_StatusTypeDef heater_turn_off (Heater_HandleTypeDef_t *hheater)
Turn off all heaters and reset to default state.
void heater_on_interupt (Heater_HandleTypeDef_t *hheater, RTC_HandleTypeDef *hrtc)
RTC interrupt handler for temperature sampling and PID.
float32_t heater_calculate_slope (Heater_HandleTypeDef_t *hheater)
Calculate temperature slope from sample buffer.
float32_t heater_calculate_mean (Heater_HandleTypeDef_t *hheater)
Calculate mean temperature from sample buffer.
void heater_set_temperature_zero (Heater_HandleTypeDef_t *hheater)
Clear the temperature sample buffer.
void heater_print_test (RTC_HandleTypeDef *hrtc, float32_t temperature)
Print temperature with timestamp (debug function).
Detailed Description
Heater control module for kiln heating coils.
Author
Dennis Rathgeb
Date
Apr 5, 2024
Controls 3 heating coils with 7 power levels (0-6):
Level 0: All coils OFF
Level 1: Coil1 PWM (50% duty)
Level 2: Coil1 ON
Level 3: Coil1 ON, Coil2 PWM
Level 4: Coil1+2 ON
Level 5: Coil1+2 ON, Coil3 PWM
Level 6: All coils ON
PWM is implemented as manual toggle with PWM_ON_SECONDS period.
Usage
Create a Heater_HandleTypeDef_t and call initHeater()
Set desired level with heater_set_level()
Call heater_set_state() periodically (more often than PWM_ON_SECONDS)
Use heater_turn_off() or set level 0 to stop heating
Door Safety
If door is opened (flag_door_open set), heater automatically goes to level 0 and resumes previous level when door closes. heater_set_state() must be called for this to take effect.
Definition in file heater.h.
Macro Definition Documentation
HEATER_ENABLE_LOG
#define HEATER_ENABLE_LOG
Enable printf logs for heater module.
Definition at line 54 of file heater.h.
INTERUPT_INTERVAL_SECONDS
#define INTERUPT_INTERVAL_SECONDS 1
RTC alarm interval in seconds (must be <= other intervals).
Definition at line 37 of file heater.h.
Referenced by heater_on_interupt(), and heater_set_temperature_zero().
MAX_MEAS_AR_LENGTH
#define MAX_MEAS_AR_LENGTH 20
Maximum length for temperature measurement arrays.
Definition at line 57 of file heater.h.
PID_CALC_INTERVAL_SECONDS
#define PID_CALC_INTERVAL_SECONDS 10
PID calculation interval in seconds.
Definition at line 43 of file heater.h.
Referenced by heater_calculate_mean(), heater_calculate_slope(), heater_on_interupt(), and heater_set_temperature_zero().
PWM_ON_SECONDS
#define PWM_ON_SECONDS 2
PWM toggle period in seconds (coil stays on for this duration).
Definition at line 34 of file heater.h.
Referenced by heater_update_pwm_coil().
TEMPERATURE_SAMPLING_INTERVAL_SECONDS
#define TEMPERATURE_SAMPLING_INTERVAL_SECONDS 1
Temperature sampling interval in seconds.
Definition at line 40 of file heater.h.
Referenced by heater_calculate_mean(), heater_calculate_slope(), and heater_on_interupt().
Enumeration Type Documentation
heater_coil_state_t
enum heater_coil_state_t
States that a heating coil can have.
Enumerator
COIL_OFF
Coil is off
COIL_ON
Coil is continuously on
COIL_PWM
Coil is in PWM mode (50% duty cycle)
Definition at line 62 of file heater.h.
Function Documentation
heater_calculate_mean()
float32_t heater_calculate_mean (Heater_HandleTypeDef_t * hheater)
Calculate mean temperature from sample buffer.
Parameters
[in] hheater Pointer to heater handle
Returns
Mean temperature in degrees C
Parameters
[in] hheater Pointer to heater handle
Returns
Mean temperature in degrees C
Uses CMSIS-DSP arm_mean_f32 for efficient calculation.
Definition at line 360 of file heater.c.
References hheater, PID_CALC_INTERVAL_SECONDS, and TEMPERATURE_SAMPLING_INTERVAL_SECONDS.
Referenced by heater_on_interupt().
heater_calculate_slope()
float32_t heater_calculate_slope (Heater_HandleTypeDef_t * hheater)
Calculate temperature slope from sample buffer.
Parameters
[in] hheater Pointer to heater handle
Returns
Temperature slope in degrees C per second
Uses linear regression to calculate the temperature rate of change from the stored temperature samples.
Calculate temperature slope from sample buffer.
Parameters
[in] hheater Pointer to heater handle
Returns
Temperature slope in degrees C per second
Uses the least squares method to fit a line to the temperature samples: slope = sum((t - mean_t) * (T - mean_T)) / sum((t - mean_t)^2)
Where t is time and T is temperature.
Definition at line 331 of file heater.c.
References hheater, PID_CALC_INTERVAL_SECONDS, and TEMPERATURE_SAMPLING_INTERVAL_SECONDS.
Referenced by heater_on_interupt().
heater_on_interupt()
void heater_on_interupt (Heater_HandleTypeDef_t * hheater, RTC_HandleTypeDef * hrtc)
RTC interrupt handler for temperature sampling and PID.
Parameters
[in,out] hheater Pointer to heater handle
[in] hrtc Pointer to RTC handle for timestamp
Called from RTC alarm interrupt (every INTERUPT_INTERVAL_SECONDS). Performs:
Temperature sampling (every TEMPERATURE_SAMPLING_INTERVAL_SECONDS)
Slope and mean calculation (every PID_CALC_INTERVAL_SECONDS)
PID calculation (TODO: not yet implemented)
RTC interrupt handler for temperature sampling and PID.
Parameters
[in,out] hheater Pointer to heater handle
[in] hrtc Pointer to RTC handle
Called from RTC alarm interrupt every INTERUPT_INTERVAL_SECONDS.
Operation:
Increment time counter
At TEMPERATURE_SAMPLING_INTERVAL: read and store temperature
At PID_CALC_INTERVAL: calculate slope and mean, then reset
Todo
Implement actual PID calculation and heater level adjustment
Definition at line 420 of file heater.c.
References heater_calculate_mean(), heater_calculate_slope(), heater_print_test(), heater_set_temperature_zero(), hheater, hrtc, INTERUPT_INTERVAL_SECONDS, max31855_get_temp_f32(), max31855_read_data(), PID_CALC_INTERVAL_SECONDS, and TEMPERATURE_SAMPLING_INTERVAL_SECONDS.
Referenced by HAL_RTC_AlarmAEventCallback().
heater_print_test()
void heater_print_test (RTC_HandleTypeDef * hrtc, float32_t temperature)
Print temperature with timestamp (debug function).
Parameters
[in] hrtc Pointer to RTC handle for timestamp
[in] temperature Temperature value to print
Print temperature with timestamp (debug function).
Parameters
[in] hrtc Pointer to RTC handle
[in] temperature Temperature value to print
Output format: HH:MM:SS,temperature Used for logging temperature data to UART.
Definition at line 395 of file heater.c.
References hrtc.
Referenced by heater_on_interupt().
heater_set_level()
HAL_StatusTypeDef heater_set_level (Heater_HandleTypeDef_t * hheater, uint8_t level)
Set the heater power level.
Parameters
[in,out] hheater Pointer to heater handle
[in] level Power level (0-6)
Returns
HAL_OK on success, HAL_ERROR for invalid level
Configures coil states according to the level mapping:
0: All OFF
1: Coil1 PWM
2: Coil1 ON
3: Coil1 ON, Coil2 PWM
4: Coil1+2 ON
5: Coil1+2 ON, Coil3 PWM
6: All ON
Set the heater power level.
Parameters
[in,out] hheater Pointer to heater handle
[in] level Power level (0-6)
Returns
HAL_OK on success, HAL_ERROR for invalid level
Level to coil state mapping:
Level Coil1 Coil2 Coil3
0 OFF OFF OFF
1 PWM OFF OFF
2 ON OFF OFF
3 ON PWM OFF
4 ON ON OFF
5 ON ON PWM
6 ON ON ON
Definition at line 252 of file heater.c.
References COIL_OFF, COIL_ON, COIL_PWM, and hheater.
Referenced by heater_check_door_state(), heater_turn_off(), and main().
heater_set_state()
HAL_StatusTypeDef heater_set_state (Heater_HandleTypeDef_t * hheater)
Apply the configured heater state to GPIO outputs.
Parameters
[in,out] hheater Pointer to heater handle
Returns
HAL_OK on success
Must be called periodically (more often than PWM_ON_SECONDS) to:
Update PWM toggling for coils in PWM mode
Check door state and pause/resume heating
Apply the configured heater state to GPIO outputs.
Parameters
[in,out] hheater Pointer to heater handle
Returns
HAL_OK on success
Checks door state first, then updates all three coils. Must be called periodically for PWM to work correctly.
Definition at line 307 of file heater.c.
References heater_check_door_state(), heater_set_coil_state(), and hheater.
Referenced by HAL_GPIO_EXTI_Callback(), and main().
heater_set_temperature_zero()
void heater_set_temperature_zero (Heater_HandleTypeDef_t * hheater)
Clear the temperature sample buffer.
Parameters
[in,out] hheater Pointer to heater handle
Sets all elements in the temperature array to zero.
Clear the temperature sample buffer.
Parameters
[in,out] hheater Pointer to heater handle
Sets all elements in the temperature array to zero.
Definition at line 378 of file heater.c.
References hheater, INTERUPT_INTERVAL_SECONDS, and PID_CALC_INTERVAL_SECONDS.
Referenced by heater_on_interupt().
heater_turn_off()
HAL_StatusTypeDef heater_turn_off (Heater_HandleTypeDef_t * hheater)
Turn off all heaters and reset to default state.
Parameters
[in,out] hheater Pointer to heater handle
Returns
HAL_OK on success
Definition at line 225 of file heater.c.
References heater_set_default_params(), heater_set_level(), and hheater.
initHeater()
HAL_StatusTypeDef initHeater (Heater_HandleTypeDef_t * hheater, MAX31855_HandleTypeDef_t * htemp, GPIO_TypeDef * coil1_port, uint16_t coil1_pin, GPIO_TypeDef * coil2_port, uint16_t coil2_pin, GPIO_TypeDef * coil3_port, uint16_t coil3_pin)
Initialize the heater module.
Parameters
[out] hheater Pointer to heater handle to initialize
[in] htemp Pointer to MAX31855 temperature sensor handle
[in] coil1_port GPIO port for coil 1
[in] coil1_pin GPIO pin for coil 1
[in] coil2_port GPIO port for coil 2
[in] coil2_pin GPIO pin for coil 2
[in] coil3_port GPIO port for coil 3
[in] coil3_pin GPIO pin for coil 3
Returns
HAL_OK on success, HAL_ERROR if hheater is NULL
Definition at line 53 of file heater.c.
References heater_set_default_params(), hheater, and htemp.
Referenced by main().