PotteryOven Kiln Controller: Core/Inc/lcd1602_rgb.h File Reference
lcd1602_rgb.h File Reference
LCD1602 RGB display driver with I2C interface.
#include <stdint.h>
#include <main.h>
#include "log.h"
#include <stdio.h>
#include "stm32f0xx_hal.h"
Data Structures
struct LCD1602_RGB_HandleTypeDef_t
Handle structure for LCD1602 RGB display.
Macros
#define LCD_ADDRESS 0x7c
#define RGB_ADDRESS 0xc0
#define WHITE 0
#define RED 1
#define GREEN 2
#define BLUE 3
#define REG_RED 0x04
#define REG_GREEN 0x03
#define REG_BLUE 0x02
#define REG_MODE1 0x00
#define REG_MODE2 0x01
#define REG_OUTPUT 0x08
#define LCD_CLEARDISPLAY 0x01
#define LCD_RETURNHOME 0x02
#define LCD_ENTRYMODESET 0x04
#define LCD_DISPLAYCONTROL 0x08
#define LCD_CURSORSHIFT 0x10
#define LCD_FUNCTIONSET 0x20
#define LCD_SETCGRAMADDR 0x40
#define LCD_SETDDRAMADDR 0x80
#define LCD_ENTRYRIGHT 0x00
#define LCD_ENTRYLEFT 0x02
#define LCD_ENTRYSHIFTINCREMENT 0x01
#define LCD_ENTRYSHIFTDECREMENT 0x00
#define LCD_DISPLAYON 0x04
#define LCD_DISPLAYOFF 0x00
#define LCD_CURSORON 0x02
#define LCD_CURSOROFF 0x00
#define LCD_BLINKON 0x01
#define LCD_BLINKOFF 0x00
#define LCD_DISPLAYMOVE 0x08
#define LCD_CURSORMOVE 0x00
#define LCD_MOVERIGHT 0x04
#define LCD_MOVELEFT 0x00
#define LCD_8BITMODE 0x10
#define LCD_4BITMODE 0x00
#define LCD_2LINE 0x08
#define LCD_1LINE 0x00
#define LCD_5x8DOTS 0x00
Functions
HAL_StatusTypeDef lcd1602_init (LCD1602_RGB_HandleTypeDef_t *hlcd, I2C_HandleTypeDef *hi2c, uint8_t cols, uint8_t rows)
Initialize the LCD display.
HAL_StatusTypeDef lcd1602_home (LCD1602_RGB_HandleTypeDef_t *hlcd)
Return cursor to home position (0,0).
HAL_StatusTypeDef lcd1602_display (LCD1602_RGB_HandleTypeDef_t *hlcd)
Turn on the display.
HAL_StatusTypeDef lcd1602_begin (LCD1602_RGB_HandleTypeDef_t *hlcd, uint8_t cols, uint8_t lines)
Begin display operation (called by init).
HAL_StatusTypeDef lcd1602_command (LCD1602_RGB_HandleTypeDef_t *hlcd, uint8_t value)
Send a command byte to the LCD.
HAL_StatusTypeDef lcd1602_send (LCD1602_RGB_HandleTypeDef_t *hlcd, uint8_t *data, uint8_t len)
Send raw data bytes to the LCD.
HAL_StatusTypeDef lcd1602_setReg (LCD1602_RGB_HandleTypeDef_t *hlcd, uint8_t addr, uint8_t data)
Write a value to an RGB controller register.
HAL_StatusTypeDef lcd1602_setRGB (LCD1602_RGB_HandleTypeDef_t *hlcd, uint8_t r, uint8_t g, uint8_t b)
Set RGB backlight color.
HAL_StatusTypeDef lcd1602_setCursor (LCD1602_RGB_HandleTypeDef_t *hlcd, uint8_t col, uint8_t row)
Set cursor position.
HAL_StatusTypeDef lcd1602_clear (LCD1602_RGB_HandleTypeDef_t *hlcd)
Clear the display.
HAL_StatusTypeDef lcd1602_BlinkLED (LCD1602_RGB_HandleTypeDef_t *hlcd)
Enable LED blinking.
HAL_StatusTypeDef lcd1602_noBlinkLED (LCD1602_RGB_HandleTypeDef_t *hlcd)
Disable LED blinking.
HAL_StatusTypeDef lcd1602_write_char (LCD1602_RGB_HandleTypeDef_t *hlcd, uint8_t value)
Write a single character to the display.
HAL_StatusTypeDef lcd1602_send_string (LCD1602_RGB_HandleTypeDef_t *hlcd, const char *str)
Write a null-terminated string to the display.
HAL_StatusTypeDef lcd1602_stopBlink (LCD1602_RGB_HandleTypeDef_t *hlcd)
Stop cursor blinking.
HAL_StatusTypeDef lcd1602_blink (LCD1602_RGB_HandleTypeDef_t *hlcd)
Enable cursor blinking.
HAL_StatusTypeDef lcd1602_noCursor (LCD1602_RGB_HandleTypeDef_t *hlcd)
Hide the cursor.
HAL_StatusTypeDef lcd1602_cursor (LCD1602_RGB_HandleTypeDef_t *hlcd)
Show the cursor.
HAL_StatusTypeDef lcd1602_scrollDisplayLeft (LCD1602_RGB_HandleTypeDef_t *hlcd)
Scroll display content left.
HAL_StatusTypeDef lcd1602_scrollDisplayRight (LCD1602_RGB_HandleTypeDef_t *hlcd)
Scroll display content right.
HAL_StatusTypeDef lcd1602_leftToRight (LCD1602_RGB_HandleTypeDef_t *hlcd)
Set text direction left-to-right.
HAL_StatusTypeDef lcd1602_rightToLeft (LCD1602_RGB_HandleTypeDef_t *hlcd)
Set text direction right-to-left.
HAL_StatusTypeDef lcd1602_noAutoscroll (LCD1602_RGB_HandleTypeDef_t *hlcd)
Disable autoscroll mode.
HAL_StatusTypeDef lcd1602_autoscroll (LCD1602_RGB_HandleTypeDef_t *hlcd)
Enable autoscroll mode.
HAL_StatusTypeDef lcd1602_customSymbol (LCD1602_RGB_HandleTypeDef_t *hlcd, uint8_t location, uint8_t charmap[])
Create a custom character in CGRAM.
HAL_StatusTypeDef lcd1602_setColorWhite (LCD1602_RGB_HandleTypeDef_t *hlcd)
Set backlight to white (255, 255, 255).
Detailed Description
LCD1602 RGB display driver with I2C interface.
Author
Dennis Rathgeb
Date
Apr 6, 2024
Driver for the Grove LCD1602 RGB backlight display. The display has two I2C addresses:
LCD controller at 0x7C
RGB backlight controller at 0xC0
Supports 4-bit mode operation with full control over display, cursor, scrolling, and RGB backlight color.
Definition in file lcd1602_rgb.h.
Function Documentation
lcd1602_autoscroll()
HAL_StatusTypeDef lcd1602_autoscroll (LCD1602_RGB_HandleTypeDef_t * hlcd)
Enable autoscroll mode.
Parameters
[in,out] hlcd Pointer to LCD handle
Returns
HAL_OK on success
Parameters
[in,out] hlcd Pointer to LCD handle
Returns
HAL_OK on success
Display shifts when characters are written to keep cursor visible.
< Shift display on write
< Set entry mode
Definition at line 399 of file lcd1602_rgb.c.
References hlcd, lcd1602_command(), LCD_ENTRYMODESET, and LCD_ENTRYSHIFTINCREMENT.
lcd1602_begin()
HAL_StatusTypeDef lcd1602_begin (LCD1602_RGB_HandleTypeDef_t * hlcd, uint8_t cols, uint8_t lines)
Begin display operation (called by init).
Parameters
[in,out] hlcd Pointer to LCD handle
[in] cols Number of columns
[in] lines Number of lines
Returns
HAL_OK on success
Begin display operation (called by init).
Parameters
[in,out] hlcd Pointer to LCD handle
[in] cols Number of columns
[in] lines Number of lines
Returns
HAL_OK on success, accumulated error code on failure
Performs the complete LCD initialization sequence:
Wait for power stabilization (50ms)
Send function set command 3 times (per HD44780 spec)
Configure display control, clear display, set entry mode
Initialize RGB backlight to white
< 2-line display
< Function set
< Function set
< Function set
< Display on
< Cursor hidden
< Cursor blink off
< Increment cursor position
< Don't shift display
< Set entry mode
< Mode register 1
< Output state register
< Mode register 2
Definition at line 46 of file lcd1602_rgb.c.
References hlcd, lcd1602_clear(), lcd1602_command(), lcd1602_display(), lcd1602_setColorWhite(), lcd1602_setReg(), LCD_2LINE, LCD_BLINKOFF, LCD_CURSOROFF, LCD_DISPLAYON, LCD_ENTRYLEFT, LCD_ENTRYMODESET, LCD_ENTRYSHIFTDECREMENT, LCD_FUNCTIONSET, REG_MODE1, REG_MODE2, and REG_OUTPUT.
Referenced by lcd1602_init().
lcd1602_blink()
HAL_StatusTypeDef lcd1602_blink (LCD1602_RGB_HandleTypeDef_t * hlcd)
Enable cursor blinking.
Parameters
[in,out] hlcd Pointer to LCD handle
Returns
HAL_OK on success
< Cursor blink on
< Display on/off control
Definition at line 305 of file lcd1602_rgb.c.
References hlcd, lcd1602_command(), LCD_BLINKON, and LCD_DISPLAYCONTROL.
lcd1602_BlinkLED()
HAL_StatusTypeDef lcd1602_BlinkLED (LCD1602_RGB_HandleTypeDef_t * hlcd)
Enable LED blinking.
Parameters
[in] hlcd Pointer to LCD handle
Returns
HAL_OK on success
Enable LED blinking.
Parameters
[in] hlcd Pointer to LCD handle
Returns
HAL_OK on success
Configures the RGB controller for blinking mode.
Definition at line 258 of file lcd1602_rgb.c.
References hlcd, and lcd1602_setReg().
lcd1602_clear()
HAL_StatusTypeDef lcd1602_clear (LCD1602_RGB_HandleTypeDef_t * hlcd)
Clear the display.
Parameters
[in] hlcd Pointer to LCD handle
Returns
HAL_OK on success
Clear the display.
Parameters
[in] hlcd Pointer to LCD handle
Returns
HAL_OK on success
Clears all display content. Requires 200ms delay for execution.
< Clear display and return cursor home
Definition at line 145 of file lcd1602_rgb.c.
References hlcd, lcd1602_command(), and LCD_CLEARDISPLAY.
Referenced by lcd1602_begin().
lcd1602_command()
HAL_StatusTypeDef lcd1602_command (LCD1602_RGB_HandleTypeDef_t * hlcd, uint8_t value)
Send a command byte to the LCD.
Parameters
[in] hlcd Pointer to LCD handle
[in] value Command byte to send
Returns
HAL_OK on success
Parameters
[in] hlcd Pointer to LCD handle
[in] value Command byte to send
Returns
HAL_OK on success
Commands are sent with 0x80 prefix to indicate command mode.
Definition at line 119 of file lcd1602_rgb.c.
References hlcd, and lcd1602_send().
Referenced by lcd1602_autoscroll(), lcd1602_begin(), lcd1602_blink(), lcd1602_clear(), lcd1602_cursor(), lcd1602_customSymbol(), lcd1602_display(), lcd1602_home(), lcd1602_leftToRight(), lcd1602_noAutoscroll(), lcd1602_noCursor(), lcd1602_rightToLeft(), lcd1602_scrollDisplayLeft(), lcd1602_scrollDisplayRight(), and lcd1602_stopBlink().
lcd1602_cursor()
HAL_StatusTypeDef lcd1602_cursor (LCD1602_RGB_HandleTypeDef_t * hlcd)
Show the cursor.
Parameters
[in,out] hlcd Pointer to LCD handle
Returns
HAL_OK on success
Show the cursor.
Parameters
[in,out] hlcd Pointer to LCD handle
Returns
HAL_OK on success
< Cursor visible
< Display on/off control
Definition at line 327 of file lcd1602_rgb.c.
References hlcd, lcd1602_command(), LCD_CURSORON, and LCD_DISPLAYCONTROL.
lcd1602_customSymbol()
HAL_StatusTypeDef lcd1602_customSymbol (LCD1602_RGB_HandleTypeDef_t * hlcd, uint8_t location, uint8_t charmap[])
Create a custom character in CGRAM.
Parameters
[in] hlcd Pointer to LCD handle
[in] location CGRAM location (0-7)
[in] charmap Array of 8 bytes defining character pattern
Returns
HAL_OK on success
Parameters
[in] hlcd Pointer to LCD handle
[in] location CGRAM location (0-7, masked to 3 bits)
[in] charmap Array of 8 bytes defining character pattern (5 bits per row)
Returns
HAL_OK on success
Custom characters are accessed by writing their location (0-7) to the display. Each byte in charmap defines one row of the 5x8 character pattern.
< Set CGRAM address
Definition at line 415 of file lcd1602_rgb.c.
References hlcd, lcd1602_command(), lcd1602_send(), and LCD_SETCGRAMADDR.
Referenced by initUI().
lcd1602_display()
HAL_StatusTypeDef lcd1602_display (LCD1602_RGB_HandleTypeDef_t * hlcd)
Turn on the display.
Parameters
[in,out] hlcd Pointer to LCD handle
Returns
HAL_OK on success
Parameters
[in,out] hlcd Pointer to LCD handle
Returns
HAL_OK on success
Sets the display on flag and sends the display control command.
< Display on
< Display on/off control
Definition at line 132 of file lcd1602_rgb.c.
References hlcd, lcd1602_command(), LCD_DISPLAYCONTROL, and LCD_DISPLAYON.
Referenced by lcd1602_begin().
lcd1602_home()
HAL_StatusTypeDef lcd1602_home (LCD1602_RGB_HandleTypeDef_t * hlcd)
Return cursor to home position (0,0).
Parameters
[in] hlcd Pointer to LCD handle
Returns
HAL_OK on success
Parameters
[in] hlcd Pointer to LCD handle
Returns
HAL_OK on success
Moves cursor to upper-left corner. Requires 200ms delay for execution.
< Return cursor to home position
Definition at line 451 of file lcd1602_rgb.c.
References hlcd, lcd1602_command(), and LCD_RETURNHOME.
lcd1602_init()
HAL_StatusTypeDef lcd1602_init (LCD1602_RGB_HandleTypeDef_t * hlcd, I2C_HandleTypeDef * hi2c, uint8_t cols, uint8_t rows)
Initialize the LCD display.
Parameters
[out] hlcd Pointer to LCD handle to initialize
[in] hi2c Pointer to I2C handle for communication
[in] cols Number of columns (typically 16)
[in] rows Number of rows (typically 2)
Returns
HAL_OK on success, error code on failure
Parameters
[out] hlcd Pointer to LCD handle to initialize
[in] hi2c Pointer to I2C handle for communication
[in] cols Number of columns (typically 16)
[in] rows Number of rows (typically 2)
Returns
HAL_OK on success, error code on failure
Stores configuration and calls lcd1602_begin for hardware initialization.
< 4-bit data interface
< 1-line display
< 5x8 dot character font
Definition at line 23 of file lcd1602_rgb.c.
References hlcd, lcd1602_begin(), LCD_1LINE, LCD_4BITMODE, and LCD_5x8DOTS.
Referenced by main().
lcd1602_leftToRight()
HAL_StatusTypeDef lcd1602_leftToRight (LCD1602_RGB_HandleTypeDef_t * hlcd)
Set text direction left-to-right.
Parameters
[in,out] hlcd Pointer to LCD handle
Returns
HAL_OK on success
Set text direction left-to-right.
Parameters
[in,out] hlcd Pointer to LCD handle
Returns
HAL_OK on success
Characters are written left to right, cursor moves right.
< Increment cursor position
< Set entry mode
Definition at line 360 of file lcd1602_rgb.c.
References hlcd, lcd1602_command(), LCD_ENTRYLEFT, and LCD_ENTRYMODESET.
lcd1602_noAutoscroll()
HAL_StatusTypeDef lcd1602_noAutoscroll (LCD1602_RGB_HandleTypeDef_t * hlcd)
Disable autoscroll mode.
Parameters
[in,out] hlcd Pointer to LCD handle
Returns
HAL_OK on success
Parameters
[in,out] hlcd Pointer to LCD handle
Returns
HAL_OK on success
Display does not shift when characters are written.
< Shift display on write
< Set entry mode
Definition at line 386 of file lcd1602_rgb.c.
References hlcd, lcd1602_command(), LCD_ENTRYMODESET, and LCD_ENTRYSHIFTINCREMENT.
lcd1602_noBlinkLED()
HAL_StatusTypeDef lcd1602_noBlinkLED (LCD1602_RGB_HandleTypeDef_t * hlcd)
Disable LED blinking.
Parameters
[in] hlcd Pointer to LCD handle
Returns
HAL_OK on success
Disable LED blinking.
Parameters
[in] hlcd Pointer to LCD handle
Returns
HAL_OK on success
Returns RGB controller to steady-on mode.
Definition at line 277 of file lcd1602_rgb.c.
References hlcd, and lcd1602_setReg().
lcd1602_noCursor()
HAL_StatusTypeDef lcd1602_noCursor (LCD1602_RGB_HandleTypeDef_t * hlcd)
Hide the cursor.
Parameters
[in,out] hlcd Pointer to LCD handle
Returns
HAL_OK on success
< Cursor visible
< Display on/off control
Definition at line 316 of file lcd1602_rgb.c.
References hlcd, lcd1602_command(), LCD_CURSORON, and LCD_DISPLAYCONTROL.
lcd1602_rightToLeft()
HAL_StatusTypeDef lcd1602_rightToLeft (LCD1602_RGB_HandleTypeDef_t * hlcd)
Set text direction right-to-left.
Parameters
[in,out] hlcd Pointer to LCD handle
Returns
HAL_OK on success
Set text direction right-to-left.
Parameters
[in,out] hlcd Pointer to LCD handle
Returns
HAL_OK on success
Characters are written right to left, cursor moves left.
< Increment cursor position
< Set entry mode
Definition at line 373 of file lcd1602_rgb.c.
References hlcd, lcd1602_command(), LCD_ENTRYLEFT, and LCD_ENTRYMODESET.
lcd1602_scrollDisplayLeft()
HAL_StatusTypeDef lcd1602_scrollDisplayLeft (LCD1602_RGB_HandleTypeDef_t * hlcd)
Scroll display content left.
Parameters
[in] hlcd Pointer to LCD handle
Returns
HAL_OK on success
Scroll display content left.
Parameters
[in] hlcd Pointer to LCD handle
Returns
HAL_OK on success
< Cursor/display shift
< Shift entire display
< Shift/move left
Definition at line 338 of file lcd1602_rgb.c.
References hlcd, lcd1602_command(), LCD_CURSORSHIFT, LCD_DISPLAYMOVE, and LCD_MOVELEFT.
lcd1602_scrollDisplayRight()
HAL_StatusTypeDef lcd1602_scrollDisplayRight (LCD1602_RGB_HandleTypeDef_t * hlcd)
Scroll display content right.
Parameters
[in] hlcd Pointer to LCD handle
Returns
HAL_OK on success
Scroll display content right.
Parameters
[in] hlcd Pointer to LCD handle
Returns
HAL_OK on success
< Cursor/display shift
< Shift entire display
< Shift/move right
Definition at line 348 of file lcd1602_rgb.c.
References hlcd, lcd1602_command(), LCD_CURSORSHIFT, LCD_DISPLAYMOVE, and LCD_MOVERIGHT.
lcd1602_send()
HAL_StatusTypeDef lcd1602_send (LCD1602_RGB_HandleTypeDef_t * hlcd, uint8_t * data, uint8_t len)
Send raw data bytes to the LCD.
Parameters
[in] hlcd Pointer to LCD handle
[in] data Pointer to data buffer
[in] len Number of bytes to send
Returns
HAL_OK on success
Send raw data bytes to the LCD.
Parameters
[in] hlcd Pointer to LCD handle
[in] data Pointer to data buffer
[in] len Number of bytes to send
Returns
HAL_OK on success
< I2C address for LCD controller
Definition at line 105 of file lcd1602_rgb.c.
References hlcd, and LCD_ADDRESS.
Referenced by lcd1602_command(), lcd1602_customSymbol(), lcd1602_setCursor(), and lcd1602_write_char().
lcd1602_send_string()
HAL_StatusTypeDef lcd1602_send_string (LCD1602_RGB_HandleTypeDef_t * hlcd, const char * str)
Write a null-terminated string to the display.
Parameters
[in] hlcd Pointer to LCD handle
[in] str Null-terminated string to write
Returns
HAL_OK on success
Parameters
[in] hlcd Pointer to LCD handle
[in] str Null-terminated string to write
Returns
HAL_OK on success
Writes each character in sequence until null terminator.
Definition at line 235 of file lcd1602_rgb.c.
References hlcd, and lcd1602_write_char().
Referenced by ui_print_lcd().
lcd1602_setColorWhite()
HAL_StatusTypeDef lcd1602_setColorWhite (LCD1602_RGB_HandleTypeDef_t * hlcd)
Set backlight to white (255, 255, 255).
Parameters
[in] hlcd Pointer to LCD handle
Returns
HAL_OK on success
Set backlight to white (255, 255, 255).
Parameters
[in] hlcd Pointer to LCD handle
Returns
HAL_OK on success
Definition at line 440 of file lcd1602_rgb.c.
References hlcd, and lcd1602_setRGB().
Referenced by lcd1602_begin().
lcd1602_setCursor()
HAL_StatusTypeDef lcd1602_setCursor (LCD1602_RGB_HandleTypeDef_t * hlcd, uint8_t col, uint8_t row)
Set cursor position.
Parameters
[in] hlcd Pointer to LCD handle
[in] col Column (0 to cols-1)
[in] row Row (0 or 1)
Returns
HAL_OK on success
Parameters
[in] hlcd Pointer to LCD handle
[in] col Column (0 to cols-1)
[in] row Row (0 or 1)
Returns
HAL_OK on success
Row 0 starts at DDRAM address 0x00, row 1 starts at 0x40.
Definition at line 205 of file lcd1602_rgb.c.
References hlcd, and lcd1602_send().
Referenced by ui_print_lcd(), and ui_print_lcd_program_symb().
lcd1602_setReg()
HAL_StatusTypeDef lcd1602_setReg (LCD1602_RGB_HandleTypeDef_t * hlcd, uint8_t addr, uint8_t data)
Write a value to an RGB controller register.
Parameters
[in] hlcd Pointer to LCD handle
[in] addr Register address
[in] data Value to write
Returns
HAL_OK on success
Parameters
[in] hlcd Pointer to LCD handle
[in] addr Register address
[in] data Value to write
Returns
HAL_OK on success
Communicates with the RGB backlight controller at RGB_ADDRESS.
< I2C address for RGB backlight controller
Definition at line 166 of file lcd1602_rgb.c.
References hlcd, and RGB_ADDRESS.
Referenced by lcd1602_begin(), lcd1602_BlinkLED(), lcd1602_noBlinkLED(), and lcd1602_setRGB().
lcd1602_setRGB()
HAL_StatusTypeDef lcd1602_setRGB (LCD1602_RGB_HandleTypeDef_t * hlcd, uint8_t r, uint8_t g, uint8_t b)
Set RGB backlight color.
Parameters
[in] hlcd Pointer to LCD handle
[in] r Red intensity (0-255)
[in] g Green intensity (0-255)
[in] b Blue intensity (0-255)
Returns
HAL_OK on success
< Red PWM register (pwm2)
< Green PWM register (pwm1)
< Blue PWM register (pwm0)
Definition at line 183 of file lcd1602_rgb.c.
References hlcd, lcd1602_setReg(), REG_BLUE, REG_GREEN, and REG_RED.
Referenced by lcd1602_setColorWhite().
lcd1602_stopBlink()
HAL_StatusTypeDef lcd1602_stopBlink (LCD1602_RGB_HandleTypeDef_t * hlcd)
Stop cursor blinking.
Parameters
[in,out] hlcd Pointer to LCD handle
Returns
HAL_OK on success
Stop cursor blinking.
Parameters
[in,out] hlcd Pointer to LCD handle
Returns
HAL_OK on success
< Cursor blink on
< Display on/off control
Definition at line 294 of file lcd1602_rgb.c.
References hlcd, lcd1602_command(), LCD_BLINKON, and LCD_DISPLAYCONTROL.
lcd1602_write_char()
HAL_StatusTypeDef lcd1602_write_char (LCD1602_RGB_HandleTypeDef_t * hlcd, uint8_t value)
Write a single character to the display.
Parameters
[in] hlcd Pointer to LCD handle
[in] value ASCII character to write
Returns
HAL_OK on success
Parameters
[in] hlcd Pointer to LCD handle
[in] value ASCII character or custom character index (0-7)
Returns
HAL_OK on success
Characters are sent with 0x40 prefix to indicate data mode.
Definition at line 221 of file lcd1602_rgb.c.
References hlcd, and lcd1602_send().
Referenced by lcd1602_send_string(), and ui_print_lcd_program_symb().