PotteryOven Kiln Controller: Core/Inc/log.h File Reference
log.h File Reference
Logging module with configurable log levels and UART output.
#include "stm32f0xx_hal.h"
Macros
#define LOG_DEBUG 0
#define LOG_INFO 1
#define LOG_WARNING 2
#define LOG_ERROR 3
#define LOG_LEVEL_THRESHOLD 0
Threshold for log message filtering.
#define REROUTE_PRINTF
Enable printf rerouting to UART.
#define PUTCHAR_PROTOTYPE int fputc(int ch, FILE *f)
Prototype for putchar redirection (non-GCC).
#define GETCHAR_PROTOTYPE int getc(FILE *f)
Prototype for getchar redirection (non-GCC).
Functions
void initLog (UART_HandleTypeDef *huart)
Initialize the logging module.
void logMsg (int logLevel, const char *format,...)
Log a message with specified log level.
Detailed Description
Logging module with configurable log levels and UART output.
Author
Dennis Rathgeb
Date
Nov 15, 2023
This module implements a logging feature with multiple logging levels: LOG_DEBUG, LOG_INFO, LOG_WARNING, LOG_ERROR
Output is sent to UART (handle passed to initLog). Printf is rerouted to UART if REROUTE_PRINTF is defined.
Todo
Implement logging feature to file
Definition in file log.h.
Macro Definition Documentation
GETCHAR_PROTOTYPE
#define GETCHAR_PROTOTYPE int getc(FILE *f)
Prototype for getchar redirection (non-GCC).
Definition at line 74 of file log.h.
Referenced by getc().
LOG_LEVEL_THRESHOLD
#define LOG_LEVEL_THRESHOLD 0
Threshold for log message filtering.
Messages with log level below this threshold will not be displayed. Set to LOG_DEBUG (0) to show all messages.
Definition at line 38 of file log.h.
Referenced by logMsg().
PUTCHAR_PROTOTYPE
#define PUTCHAR_PROTOTYPE int fputc(int ch, FILE *f)
Prototype for putchar redirection (non-GCC).
Definition at line 72 of file log.h.
Referenced by fputc().
REROUTE_PRINTF
#define REROUTE_PRINTF
Enable printf rerouting to UART.
When defined, printf output is redirected to the UART handle passed to initLog().
Definition at line 46 of file log.h.
Function Documentation
initLog()
void initLog (UART_HandleTypeDef * huart)
Initialize the logging module.
Parameters
[in] huart Pointer to UART handle for log output
[in] huart Pointer to UART handle for log output
Stores the UART handle for use by logMsg and printf redirection.
Definition at line 29 of file log.c.
References hlog_huart.
Referenced by main().
logMsg()
void logMsg (int logLevel, const char * format, ...)
Log a message with specified log level.
Parameters
[in] logLevel Log level (LOG_DEBUG, LOG_INFO, LOG_WARNING, LOG_ERROR)
[in] format Printf-style format string
[in] ... Variable arguments for format string
Messages are only output if logLevel >= LOG_LEVEL_THRESHOLD
Parameters
[in] logLevel Log level (LOG_DEBUG, LOG_INFO, LOG_WARNING, LOG_ERROR)
[in] format Printf-style format string
[in] ... Variable arguments for format string
Messages are only output if logLevel >= LOG_LEVEL_THRESHOLD. Output is sent to UART via printf (which is rerouted to UART).
Definition at line 42 of file log.c.
References LOG_LEVEL_THRESHOLD.
Referenced by event_diplay_type(), initEvent(), ui_update_create_program(), ui_update_create_program_detailed(), ui_update_program_detailed(), ui_update_programs(), ui_update_programs_overview(), ui_update_setpoint(), ui_update_settings(), and ui_update_settings_overview().