PotteryOven Kiln Controller: Core/Src/main.c File Reference
main.c File Reference
: Main program body
#include "main.h"
#include <stdio.h>
#include "log.h"
#include "MAX31855.h"
#include "heater.h"
#include "lcd1602_rgb.h"
#include "encoder.h"
#include "ui.h"
#include "event.h"
#include "pid.h"
Macros
#define SW_C_DEBOUNCE_TIME 20
#define TEMPERATURE_READ_INTERVAL_SECONDS 0x1;
#define DISABLE_HEATER_DOOR_DETECTION
Functions
void SystemClock_Config (void)
System Clock Configuration.
static void MX_GPIO_Init (void)
GPIO Initialization Function.
static void MX_I2C1_Init (void)
I2C1 Initialization Function.
static void MX_SPI2_Init (void)
SPI2 Initialization Function.
static void MX_USART1_UART_Init (void)
USART1 Initialization Function.
static void MX_RTC_Init (void)
RTC Initialization Function.
static void MX_TIM3_Init (void)
TIM3 Initialization Function.
int main (void)
The application entry point.
void HAL_RTC_AlarmAEventCallback (RTC_HandleTypeDef *hrtc)
void HAL_TIM_IC_CaptureCallback (TIM_HandleTypeDef *htim)
void HAL_GPIO_EXTI_Callback (uint16_t GPIO_Pin)
void Error_Handler (void)
This function is executed in case of error occurrence.
Variables
I2C_HandleTypeDef hi2c1
RTC_HandleTypeDef hrtc
SPI_HandleTypeDef hspi2
TIM_HandleTypeDef htim3
UART_HandleTypeDef huart1
uint32_t sw_c_last_interrupt_time = 0
uint8_t sw_c_flag
MAX31855_HandleTypeDef_t htemp
LCD1602_RGB_HandleTypeDef_t hlcd
Heater_HandleTypeDef_t hheater
Encoder_HandleTypeDef_t hencoder
Ui_HandleTypeDef_t hui
PID_HandletypeDef_t hpid
Event_Queue_HandleTypeDef_t hevent_queue
uint8_t counter = 0
Detailed Description
: Main program body
Attention
Copyright (c) 2024 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file main.c.
Macro Definition Documentation
DISABLE_HEATER_DOOR_DETECTION
#define DISABLE_HEATER_DOOR_DETECTION
Definition at line 47 of file main.c.
SW_C_DEBOUNCE_TIME
#define SW_C_DEBOUNCE_TIME 20
Definition at line 43 of file main.c.
Referenced by HAL_GPIO_EXTI_Callback().
TEMPERATURE_READ_INTERVAL_SECONDS
#define TEMPERATURE_READ_INTERVAL_SECONDS 0x1;
Definition at line 46 of file main.c.
Function Documentation
Error_Handler()
void Error_Handler (void)
This function is executed in case of error occurrence.
Return values
None
Definition at line 654 of file main.c.
Referenced by MX_I2C1_Init(), MX_RTC_Init(), MX_SPI2_Init(), MX_TIM3_Init(), MX_USART1_UART_Init(), and SystemClock_Config().
HAL_GPIO_EXTI_Callback()
void HAL_GPIO_EXTI_Callback (uint16_t GPIO_Pin)
Definition at line 583 of file main.c.
References BUT1, BUT1_Pin, BUT2, BUT2_Pin, BUT3, BUT3_Pin, BUT4, BUT4_Pin, BUT5_Pin, ENC_A_Pin, ENC_B_Pin, encoder_callback(), event_enqueue(), heater_set_state(), hencoder, hevent_queue, SW_C_DEBOUNCE_TIME, sw_c_flag, SW_C_GPIO_Port, sw_c_last_interrupt_time, and SW_C_Pin.
HAL_RTC_AlarmAEventCallback()
void HAL_RTC_AlarmAEventCallback (RTC_HandleTypeDef * hrtc)
Definition at line 573 of file main.c.
References heater_on_interupt(), hheater, and hrtc.
HAL_TIM_IC_CaptureCallback()
void HAL_TIM_IC_CaptureCallback (TIM_HandleTypeDef * htim)
Definition at line 579 of file main.c.
References encoder_callback(), and hencoder.
main()
int main (void)
The application entry point.
Return values
int
Definition at line 112 of file main.c.
References BUT5_GPIO_Port, BUT5_Pin, ENC_A_GPIO_Port, ENC_A_Pin, ENC_B_GPIO_Port, ENC_B_Pin, heater_set_level(), heater_set_state(), hencoder, hevent_queue, hheater, hi2c1, hlcd, hspi2, htemp, huart1, hui, init_Encoder(), initEvent(), initHeater(), initLog(), initUI(), lcd1602_init(), max31855_init(), MX_GPIO_Init(), MX_I2C1_Init(), MX_RTC_Init(), MX_SPI2_Init(), MX_TIM3_Init(), MX_USART1_UART_Init(), SW1_GPIO_Port, SW1_Pin, SW2_GPIO_Port, SW2_Pin, SW3_GPIO_Port, SW3_Pin, and SystemClock_Config().
MX_GPIO_Init()
void MX_GPIO_Init (void) static
GPIO Initialization Function.
Parameters
None
Return values
None
Definition at line 502 of file main.c.
References BUT1_Pin, BUT2_Pin, BUT3_Pin, BUT4_Pin, BUT5_GPIO_Port, BUT5_Pin, ENC_B_Pin, SPI2_NSS_GPIO_Port, SPI2_NSS_Pin, SW1_Pin, SW2_Pin, SW3_Pin, SW_C_GPIO_Port, and SW_C_Pin.
Referenced by main().
MX_I2C1_Init()
void MX_I2C1_Init (void) static
I2C1 Initialization Function.
Parameters
None
Return values
None
Configure Analogue filter
Configure Digital filter
Definition at line 246 of file main.c.
References Error_Handler(), and hi2c1.
Referenced by main().
MX_RTC_Init()
void MX_RTC_Init (void) static
RTC Initialization Function.
Parameters
None
Return values
None
Initialize RTC Only
Initialize RTC and set the Time and Date
Enable the Alarm A
Definition at line 294 of file main.c.
References Error_Handler(), and hrtc.
Referenced by main().
MX_SPI2_Init()
void MX_SPI2_Init (void) static
SPI2 Initialization Function.
Parameters
None
Return values
None
Definition at line 376 of file main.c.
References Error_Handler(), and hspi2.
Referenced by main().
MX_TIM3_Init()
void MX_TIM3_Init (void) static
TIM3 Initialization Function.
Parameters
None
Return values
None
Definition at line 416 of file main.c.
References Error_Handler(), and htim3.
Referenced by main().
MX_USART1_UART_Init()
void MX_USART1_UART_Init (void) static
USART1 Initialization Function.
Parameters
None
Return values
None
Definition at line 467 of file main.c.
References Error_Handler(), and huart1.
Referenced by main().
SystemClock_Config()
void SystemClock_Config (void)
System Clock Configuration.
Return values
None
Initializes the RCC Oscillators according to the specified parameters in the RCC_OscInitTypeDef structure.
Initializes the CPU, AHB and APB buses clocks
Definition at line 199 of file main.c.
References Error_Handler().
Referenced by main().
Variable Documentation
counter
uint8_t counter = 0
Definition at line 578 of file main.c.
hencoder
Encoder_HandleTypeDef_t hencoder
Definition at line 78 of file main.c.
Referenced by encoder_callback(), encoder_get_direction(), encoder_get_position(), encoder_get_state(), HAL_GPIO_EXTI_Callback(), HAL_TIM_IC_CaptureCallback(), init_Encoder(), main(), and update_position().
hevent_queue
Event_Queue_HandleTypeDef_t hevent_queue
Definition at line 84 of file main.c.
Referenced by HAL_GPIO_EXTI_Callback(), and main().
hheater
Heater_HandleTypeDef_t hheater
Definition at line 76 of file main.c.
Referenced by HAL_RTC_AlarmAEventCallback(), heater_calculate_mean(), heater_calculate_slope(), heater_check_door_state(), heater_on_interupt(), heater_set_default_params(), heater_set_level(), heater_set_state(), heater_set_temperature_zero(), heater_turn_off(), initHeater(), and main().
hi2c1
I2C_HandleTypeDef hi2c1
Definition at line 56 of file main.c.
Referenced by main(), and MX_I2C1_Init().
hlcd
LCD1602_RGB_HandleTypeDef_t hlcd
Definition at line 74 of file main.c.
Referenced by initUI(), lcd1602_autoscroll(), lcd1602_begin(), lcd1602_blink(), lcd1602_BlinkLED(), lcd1602_clear(), lcd1602_command(), lcd1602_cursor(), lcd1602_customSymbol(), lcd1602_display(), lcd1602_home(), lcd1602_init(), lcd1602_leftToRight(), lcd1602_noAutoscroll(), lcd1602_noBlinkLED(), lcd1602_noCursor(), lcd1602_rightToLeft(), lcd1602_scrollDisplayLeft(), lcd1602_scrollDisplayRight(), lcd1602_send(), lcd1602_send_string(), lcd1602_setColorWhite(), lcd1602_setCursor(), lcd1602_setReg(), lcd1602_setRGB(), lcd1602_stopBlink(), lcd1602_write_char(), and main().
hpid
PID_HandletypeDef_t hpid
Definition at line 82 of file main.c.
Referenced by PID_CalculateOutput(), PID_Init(), and PID_UpdateParameters().
hrtc
RTC_HandleTypeDef hrtc
Definition at line 58 of file main.c.
Referenced by HAL_RTC_AlarmAEventCallback(), heater_on_interupt(), heater_print_test(), and MX_RTC_Init().
hspi2
SPI_HandleTypeDef hspi2
Definition at line 60 of file main.c.
Referenced by main(), and MX_SPI2_Init().
htemp
MAX31855_HandleTypeDef_t htemp
Definition at line 72 of file main.c.
Referenced by initHeater(), and main().
htim3
TIM_HandleTypeDef htim3
Definition at line 62 of file main.c.
Referenced by MX_TIM3_Init().
huart1
UART_HandleTypeDef huart1
Definition at line 64 of file main.c.
Referenced by main(), and MX_USART1_UART_Init().
hui
Ui_HandleTypeDef_t hui
Definition at line 80 of file main.c.
Referenced by main().
sw_c_flag
uint8_t sw_c_flag
Definition at line 70 of file main.c.
Referenced by HAL_GPIO_EXTI_Callback().
sw_c_last_interrupt_time
uint32_t sw_c_last_interrupt_time = 0
Definition at line 69 of file main.c.
Referenced by HAL_GPIO_EXTI_Callback().