PotteryOven Kiln Controller: Core/Inc/MAX31855.h File Reference
MAX31855.h File Reference
MAX31855 thermocouple-to-digital converter driver.
#include "stm32f0xx_hal.h"
#include "main.h"
#include "arm_math.h"
#include "../Inc/MAX31855.h"
Data Structures
struct max31855_payload_t
Parsed payload structure for MAX31855 data.
struct MAX31855_HandleTypeDef_t
Handle structure for MAX31855 device.
Macros
#define MAX31855_PAYLOAD_LENGTH 32
Total payload length in bits from MAX31855.
#define MAX31855_TIMEOUT 1000000
SPI receive timeout in microseconds.
Functions
HAL_StatusTypeDef max31855_init (MAX31855_HandleTypeDef_t *hmax31855, SPI_HandleTypeDef *hspi)
Initialize the MAX31855 driver.
void max_31855_print_max31855_payload_binary (MAX31855_HandleTypeDef_t *hmax31855)
Print parsed payload in binary format (debug function).
void max_31855_print_payload (MAX31855_HandleTypeDef_t *hmax31855)
Print payload values in human-readable format (debug function).
HAL_StatusTypeDef max31855_read_data (MAX31855_HandleTypeDef_t *hmax31855)
Read data from MAX31855 via SPI.
uint16_t max31855_get_temp_sign (MAX31855_HandleTypeDef_t *hmax31855)
Get thermocouple temperature sign.
uint16_t max31855_get_temp_val (MAX31855_HandleTypeDef_t *hmax31855)
Get thermocouple temperature integer value.
uint16_t max31855_get_temp_frac (MAX31855_HandleTypeDef_t *hmax31855)
Get thermocouple temperature fractional value.
uint16_t max31855_get_int_temp_sign (MAX31855_HandleTypeDef_t *hmax31855)
Get reference junction (internal) temperature sign.
uint16_t max31855_get_int_temp_val (MAX31855_HandleTypeDef_t *hmax31855)
Get reference junction temperature integer value.
uint16_t max31855_get_int_temp_frac (MAX31855_HandleTypeDef_t *hmax31855)
Get reference junction temperature fractional value.
float32_t max31855_get_temp_f32 (MAX31855_HandleTypeDef_t *hmax31855)
Get thermocouple temperature as float32.
Detailed Description
MAX31855 thermocouple-to-digital converter driver.
Author
Dennis Rathgeb
Date
Mar 31, 2024
Driver for the MAX31855 cold-junction compensated thermocouple-to-digital converter. Communicates via SPI to read thermocouple and reference junction temperatures with fault detection.
Note
The MAX31855 outputs 32 bits of data per read:
Bits 31-18: Thermocouple temperature (14-bit, signed, 0.25C resolution)
Bit 17: Reserved
Bit 16: Fault flag
Bits 15-4: Reference junction temperature (12-bit, signed, 0.0625C resolution)
Bit 3: Reserved
Bit 2: SCV fault (short to VCC)
Bit 1: SCG fault (short to GND)
Bit 0: OC fault (open circuit)
Todo
Verify bitfield byte order is correct (D31 should be first transmitted)
Definition in file MAX31855.h.
Macro Definition Documentation
MAX31855_PAYLOAD_LENGTH
#define MAX31855_PAYLOAD_LENGTH 32
Total payload length in bits from MAX31855.
Definition at line 32 of file MAX31855.h.
Referenced by max31855_read_data().
MAX31855_TIMEOUT
#define MAX31855_TIMEOUT 1000000
SPI receive timeout in microseconds.
Definition at line 35 of file MAX31855.h.
Referenced by max31855_read_data().
Function Documentation
max31855_get_int_temp_frac()
uint16_t max31855_get_int_temp_frac (MAX31855_HandleTypeDef_t * hmax31855)
Get reference junction temperature fractional value.
Parameters
[in] hmax31855 Pointer to MAX31855 handle
Returns
Fractional value
Referenced by max_31855_print_payload().
max31855_get_int_temp_sign()
uint16_t max31855_get_int_temp_sign (MAX31855_HandleTypeDef_t * hmax31855)
Get reference junction (internal) temperature sign.
Parameters
[in] hmax31855 Pointer to MAX31855 handle
Returns
1 if temperature is negative, 0 if positive
Referenced by max_31855_print_payload().
max31855_get_int_temp_val()
uint16_t max31855_get_int_temp_val (MAX31855_HandleTypeDef_t * hmax31855)
Get reference junction temperature integer value.
Parameters
[in] hmax31855 Pointer to MAX31855 handle
Returns
Unsigned temperature value
Referenced by max_31855_print_payload().
max31855_get_temp_f32()
float32_t max31855_get_temp_f32 (MAX31855_HandleTypeDef_t * hmax31855)
Get thermocouple temperature as float32.
Parameters
[in] hmax31855 Pointer to MAX31855 handle
Returns
Temperature in degrees Celsius as float32_t
Precondition
Call max31855_read_data() first to get current value
Parameters
[in] hmax31855 Pointer to MAX31855 handle
Returns
Temperature in degrees Celsius as float32_t
Precondition
Call max31855_read_data() first to get current value
Combines sign, integer, and fractional parts into a single float value.
Definition at line 151 of file MAX31855.c.
References max31855_get_temp_sign(), max31855_get_temp_val(), MAX31855_HandleTypeDef_t::payload, temp_sign, and max31855_payload_t::therm_temp_fractual_value.
Referenced by heater_on_interupt().
max31855_get_temp_frac()
uint16_t max31855_get_temp_frac (MAX31855_HandleTypeDef_t * hmax31855)
Get thermocouple temperature fractional value.
Parameters
[in] hmax31855 Pointer to MAX31855 handle
Returns
Fractional value as integer (e.g., 75 for 0.75C)
Precondition
Call max31855_read_data() first to get current value
Parameters
[in] hmax31855 Pointer to MAX31855 handle
Returns
Fractional part as integer in 0.25C steps (0, 25, 50, or 75)
Precondition
Call max31855_read_data() first to get current value
The fractional value is stored as 2 bits representing 0.25C increments. This function returns the value multiplied by 25 for easier display.
Definition at line 138 of file MAX31855.c.
References MAX31855_HandleTypeDef_t::payload, and max31855_payload_t::therm_temp_fractual_value.
Referenced by max_31855_print_payload().
max31855_get_temp_sign()
uint16_t max31855_get_temp_sign (MAX31855_HandleTypeDef_t * hmax31855)
Get thermocouple temperature sign.
Parameters
[in] hmax31855 Pointer to MAX31855 handle
Returns
1 if temperature is negative, 0 if positive
Precondition
Call max31855_read_data() first to get current value
Definition at line 106 of file MAX31855.c.
References MAX31855_HandleTypeDef_t::payload, and max31855_payload_t::therm_temp_sign.
Referenced by max31855_get_temp_f32(), and max_31855_print_payload().
max31855_get_temp_val()
uint16_t max31855_get_temp_val (MAX31855_HandleTypeDef_t * hmax31855)
Get thermocouple temperature integer value.
Parameters
[in] hmax31855 Pointer to MAX31855 handle
Returns
Unsigned temperature value (check sign separately)
Precondition
Call max31855_read_data() first to get current value
Parameters
[in] hmax31855 Pointer to MAX31855 handle
Returns
Unsigned temperature value
Precondition
Call max31855_read_data() first to get current value
For negative temperatures, returns two's complement converted value.
Definition at line 119 of file MAX31855.c.
References MAX31855_HandleTypeDef_t::payload, max31855_payload_t::therm_temp_sign, and max31855_payload_t::therm_temp_value.
Referenced by max31855_get_temp_f32(), and max_31855_print_payload().
max31855_init()
HAL_StatusTypeDef max31855_init (MAX31855_HandleTypeDef_t * hmax31855, SPI_HandleTypeDef * hspi)
Initialize the MAX31855 driver.
Parameters
[out] hmax31855 Pointer to MAX31855 handle to initialize
[in] hspi Pointer to SPI handle for communication
Returns
HAL_OK on success
Parameters
[out] hmax31855 Pointer to MAX31855 handle to initialize
[in] hspi Pointer to SPI handle for communication
Returns
HAL_OK on success
Stores SPI handle and sets chip select (NSS) pin high (inactive).
Definition at line 23 of file MAX31855.c.
References MAX31855_HandleTypeDef_t::hspi, SPI2_NSS_GPIO_Port, and SPI2_NSS_Pin.
Referenced by main().
max31855_read_data()
HAL_StatusTypeDef max31855_read_data (MAX31855_HandleTypeDef_t * hmax31855)
Read data from MAX31855 via SPI.
Parameters
[in,out] hmax31855 Pointer to MAX31855 handle
Returns
HAL_OK on success, HAL_ERROR on failure
Performs blocking SPI read and updates both raw_payload and parsed payload fields.
Todo
Implement non-blocking (DMA) version
Parameters
[in,out] hmax31855 Pointer to MAX31855 handle
Returns
HAL_OK on success, HAL_ERROR on failure
Performs blocking SPI read:
Asserts chip select (NSS low)
Reads 4 bytes (32 bits) from MAX31855
Deasserts chip select (NSS high)
Parses raw data into payload structure
Todo
Implement non-blocking (DMA) version for better performance
Definition at line 76 of file MAX31855.c.
References MAX31855_HandleTypeDef_t::hspi, MAX31855_PAYLOAD_LENGTH, MAX31855_TIMEOUT, max31855_update_payload(), MAX31855_HandleTypeDef_t::raw_payload, SPI2_NSS_GPIO_Port, and SPI2_NSS_Pin.
Referenced by heater_on_interupt().
max_31855_print_max31855_payload_binary()
void max_31855_print_max31855_payload_binary (MAX31855_HandleTypeDef_t * hmax31855)
Print parsed payload in binary format (debug function).
Parameters
[in] hmax31855 Pointer to MAX31855 handle
Print parsed payload in binary format (debug function).
Parameters
[in] hmax31855 Pointer to MAX31855 handle
Outputs each field of the parsed payload with its binary representation. Useful for debugging bit extraction logic.
Definition at line 248 of file MAX31855.c.
References max31855_payload_t::fault, max31855_payload_t::int_temp_fractual_value, max31855_payload_t::int_temp_sign, max31855_payload_t::int_temp_value, max_31855_print_payload(), max31855_payload_t::oc_fault, MAX31855_HandleTypeDef_t::payload, print_binary(), print_raw_payload_in_binary(), max31855_payload_t::scg_fault, max31855_payload_t::scv_fault, max31855_payload_t::therm_temp_fractual_value, max31855_payload_t::therm_temp_sign, and max31855_payload_t::therm_temp_value.
max_31855_print_payload()
void max_31855_print_payload (MAX31855_HandleTypeDef_t * hmax31855)
Print payload values in human-readable format (debug function).
Parameters
[in] hmax31855 Pointer to MAX31855 handle
Print payload values in human-readable format (debug function).
Parameters
[in] hmax31855 Pointer to MAX31855 handle
Outputs internal and thermocouple temperatures plus fault status.
Definition at line 200 of file MAX31855.c.
References max31855_payload_t::fault, max31855_get_int_temp_frac(), max31855_get_int_temp_sign(), max31855_get_int_temp_val(), max31855_get_temp_frac(), max31855_get_temp_sign(), max31855_get_temp_val(), max31855_payload_t::oc_fault, MAX31855_HandleTypeDef_t::payload, print_raw_payload_in_binary(), max31855_payload_t::scg_fault, and max31855_payload_t::scv_fault.
Referenced by max_31855_print_max31855_payload_binary().