PotteryOven Kiln Controller: Core/Src/MAX31855.c File Reference
MAX31855.c File Reference
Implementation of MAX31855 thermocouple-to-digital converter driver.
#include "MAX31855.h"
#include "log.h"
#include <stdio.h>
Functions
HAL_StatusTypeDef max31855_init (MAX31855_HandleTypeDef_t *hmax31855, SPI_HandleTypeDef *hspi)
Initialize the MAX31855 driver.
static HAL_StatusTypeDef max31855_update_payload (MAX31855_HandleTypeDef_t *hmax31855)
Parse raw SPI data into payload structure fields.
HAL_StatusTypeDef max31855_read_data (MAX31855_HandleTypeDef_t *hmax31855)
Read data from MAX31855 via SPI.
uint16_t max31855_get_temp_sign (MAX31855_HandleTypeDef_t *hmax31855)
Get thermocouple temperature sign.
uint16_t max31855_get_temp_val (MAX31855_HandleTypeDef_t *hmax31855)
Get thermocouple temperature integer value.
uint16_t max31855_get_temp_frac (MAX31855_HandleTypeDef_t *hmax31855)
Get thermocouple temperature fractional value.
float32_t max31855_get_temp_f32 (MAX31855_HandleTypeDef_t *hmax31855)
Get thermocouple temperature as float32.
static void print_binary_2 (uint8_t byte)
Print a single byte in binary format.
static void print_raw_payload_in_binary (MAX31855_HandleTypeDef_t *hmax31855)
Print raw payload bytes in binary format.
void max_31855_print_payload (MAX31855_HandleTypeDef_t *hmax31855)
Print payload values in human-readable format.
void print_binary (uint16_t value, int num_bits)
Print a value in binary format with specified number of bits.
void max_31855_print_max31855_payload_binary (MAX31855_HandleTypeDef_t *hmax31855)
Print all payload fields in binary format.
Detailed Description
Implementation of MAX31855 thermocouple-to-digital converter driver.
Author
Dennis Rathgeb
Date
Mar 31, 2024
Implements SPI communication with MAX31855 for temperature reading and fault detection.
Definition in file MAX31855.c.
Function Documentation
max31855_get_temp_f32()
float32_t max31855_get_temp_f32 (MAX31855_HandleTypeDef_t * hmax31855)
Get thermocouple temperature as float32.
Parameters
[in] hmax31855 Pointer to MAX31855 handle
Returns
Temperature in degrees Celsius as float32_t
Precondition
Call max31855_read_data() first to get current value
Combines sign, integer, and fractional parts into a single float value.
Definition at line 151 of file MAX31855.c.
References max31855_get_temp_sign(), max31855_get_temp_val(), MAX31855_HandleTypeDef_t::payload, temp_sign, and max31855_payload_t::therm_temp_fractual_value.
Referenced by heater_on_interupt().
max31855_get_temp_frac()
uint16_t max31855_get_temp_frac (MAX31855_HandleTypeDef_t * hmax31855)
Get thermocouple temperature fractional value.
Parameters
[in] hmax31855 Pointer to MAX31855 handle
Returns
Fractional part as integer in 0.25C steps (0, 25, 50, or 75)
Precondition
Call max31855_read_data() first to get current value
The fractional value is stored as 2 bits representing 0.25C increments. This function returns the value multiplied by 25 for easier display.
Definition at line 138 of file MAX31855.c.
References MAX31855_HandleTypeDef_t::payload, and max31855_payload_t::therm_temp_fractual_value.
Referenced by max_31855_print_payload().
max31855_get_temp_sign()
uint16_t max31855_get_temp_sign (MAX31855_HandleTypeDef_t * hmax31855)
Get thermocouple temperature sign.
Parameters
[in] hmax31855 Pointer to MAX31855 handle
Returns
1 if temperature is negative, 0 if positive
Precondition
Call max31855_read_data() first to get current value
Definition at line 106 of file MAX31855.c.
References MAX31855_HandleTypeDef_t::payload, and max31855_payload_t::therm_temp_sign.
Referenced by max31855_get_temp_f32(), and max_31855_print_payload().
max31855_get_temp_val()
uint16_t max31855_get_temp_val (MAX31855_HandleTypeDef_t * hmax31855)
Get thermocouple temperature integer value.
Parameters
[in] hmax31855 Pointer to MAX31855 handle
Returns
Unsigned temperature value
Precondition
Call max31855_read_data() first to get current value
For negative temperatures, returns two's complement converted value.
Definition at line 119 of file MAX31855.c.
References MAX31855_HandleTypeDef_t::payload, max31855_payload_t::therm_temp_sign, and max31855_payload_t::therm_temp_value.
Referenced by max31855_get_temp_f32(), and max_31855_print_payload().
max31855_init()
HAL_StatusTypeDef max31855_init (MAX31855_HandleTypeDef_t * hmax31855, SPI_HandleTypeDef * hspi)
Initialize the MAX31855 driver.
Parameters
[out] hmax31855 Pointer to MAX31855 handle to initialize
[in] hspi Pointer to SPI handle for communication
Returns
HAL_OK on success
Stores SPI handle and sets chip select (NSS) pin high (inactive).
Definition at line 23 of file MAX31855.c.
References MAX31855_HandleTypeDef_t::hspi, SPI2_NSS_GPIO_Port, and SPI2_NSS_Pin.
Referenced by main().
max31855_read_data()
HAL_StatusTypeDef max31855_read_data (MAX31855_HandleTypeDef_t * hmax31855)
Read data from MAX31855 via SPI.
Parameters
[in,out] hmax31855 Pointer to MAX31855 handle
Returns
HAL_OK on success, HAL_ERROR on failure
Performs blocking SPI read:
Asserts chip select (NSS low)
Reads 4 bytes (32 bits) from MAX31855
Deasserts chip select (NSS high)
Parses raw data into payload structure
Todo
Implement non-blocking (DMA) version for better performance
Definition at line 76 of file MAX31855.c.
References MAX31855_HandleTypeDef_t::hspi, MAX31855_PAYLOAD_LENGTH, MAX31855_TIMEOUT, max31855_update_payload(), MAX31855_HandleTypeDef_t::raw_payload, SPI2_NSS_GPIO_Port, and SPI2_NSS_Pin.
Referenced by heater_on_interupt().
max31855_update_payload()
HAL_StatusTypeDef max31855_update_payload (MAX31855_HandleTypeDef_t * hmax31855) static
Parse raw SPI data into payload structure fields.
Parameters
[in,out] hmax31855 Pointer to MAX31855 handle
Returns
HAL_OK on success, HAL_ERROR if handle is NULL
Extracts all fields from the 32-bit raw data using bitwise operations. The MAX31855 transmits MSB first (D31 first).
Definition at line 38 of file MAX31855.c.
References max31855_payload_t::fault, max31855_payload_t::int_temp_fractual_value, max31855_payload_t::int_temp_sign, max31855_payload_t::int_temp_value, max31855_payload_t::oc_fault, MAX31855_HandleTypeDef_t::payload, MAX31855_HandleTypeDef_t::raw_payload, max31855_payload_t::scg_fault, max31855_payload_t::scv_fault, max31855_payload_t::therm_temp_fractual_value, max31855_payload_t::therm_temp_sign, and max31855_payload_t::therm_temp_value.
Referenced by max31855_read_data().
max_31855_print_max31855_payload_binary()
void max_31855_print_max31855_payload_binary (MAX31855_HandleTypeDef_t * hmax31855)
Print all payload fields in binary format.
Print parsed payload in binary format (debug function).
Parameters
[in] hmax31855 Pointer to MAX31855 handle
Outputs each field of the parsed payload with its binary representation. Useful for debugging bit extraction logic.
Definition at line 248 of file MAX31855.c.
References max31855_payload_t::fault, max31855_payload_t::int_temp_fractual_value, max31855_payload_t::int_temp_sign, max31855_payload_t::int_temp_value, max_31855_print_payload(), max31855_payload_t::oc_fault, MAX31855_HandleTypeDef_t::payload, print_binary(), print_raw_payload_in_binary(), max31855_payload_t::scg_fault, max31855_payload_t::scv_fault, max31855_payload_t::therm_temp_fractual_value, max31855_payload_t::therm_temp_sign, and max31855_payload_t::therm_temp_value.
max_31855_print_payload()
void max_31855_print_payload (MAX31855_HandleTypeDef_t * hmax31855)
Print payload values in human-readable format.
Print payload values in human-readable format (debug function).
Parameters
[in] hmax31855 Pointer to MAX31855 handle
Outputs internal and thermocouple temperatures plus fault status.
Definition at line 200 of file MAX31855.c.
References max31855_payload_t::fault, max31855_get_int_temp_frac(), max31855_get_int_temp_sign(), max31855_get_int_temp_val(), max31855_get_temp_frac(), max31855_get_temp_sign(), max31855_get_temp_val(), max31855_payload_t::oc_fault, MAX31855_HandleTypeDef_t::payload, print_raw_payload_in_binary(), max31855_payload_t::scg_fault, and max31855_payload_t::scv_fault.
Referenced by max_31855_print_max31855_payload_binary().
print_binary()
void print_binary (uint16_t value, int num_bits)
Print a value in binary format with specified number of bits.
Parameters
[in] value Value to print
[in] num_bits Number of bits to display
Definition at line 235 of file MAX31855.c.
Referenced by max_31855_print_max31855_payload_binary().
print_binary_2()
void print_binary_2 (uint8_t byte) static
Print a single byte in binary format.
Parameters
[in] byte Byte to print
Outputs 8 bits from MSB to LSB.
Definition at line 174 of file MAX31855.c.
Referenced by print_raw_payload_in_binary().
print_raw_payload_in_binary()
void print_raw_payload_in_binary (MAX31855_HandleTypeDef_t * hmax31855) static
Print raw payload bytes in binary format.
Parameters
[in] hmax31855 Pointer to MAX31855 handle
Outputs all 4 bytes separated by spaces.
Definition at line 186 of file MAX31855.c.
References print_binary_2(), and MAX31855_HandleTypeDef_t::raw_payload.
Referenced by max_31855_print_max31855_payload_binary(), and max_31855_print_payload().