PotteryOven Kiln Controller: Core/Inc/ui.h File Reference
ui.h File Reference
User interface module for menu-driven LCD control.
#include <stdio.h>
#include <stdint.h>
#include "main.h"
#include "log.h"
#include <stm32f0xx_hal.h>
#include "lcd1602_rgb.h"
#include "arm_math.h"
#include "event.h"
Data Structures
struct ui_program_t
Structure for a firing program.
struct ui_programs_t
Structure for storing multiple programs.
struct ui_setting_t
Structure for a single setting.
struct ui_settings_t
Structure for storing multiple settings.
struct Ui_HandleTypeDef_t
Handle structure for UI state.
Macros
#define UI_ENABLE_LOG
Enable debug logging for UI module.
#define UI_LCD_CHAR_SIZE 17
LCD character buffer size (16 chars + null).
#define MAX_TEMPERATURE 1300
Maximum allowed temperature in degrees C.
#define MAX_GRADIENT 650
Maximum allowed gradient in degrees C per hour (both positive and negative).
#define MAX_SETTING_TIME 20
Maximum allowed time setting value.
#define MAX_SETTING 20
Maximum allowed setting value (both positive and negative).
#define BUTTON_INC 5
Increment step for button-based value changes.
#define ENC_INC 20
Increment step for encoder-based value changes.
#define BUTTON_INC_FLOAT_MILLIS 100
Increment for button-based float value changes (in millis, divide by 1000).
#define ENC_INC_FLOAT_MILLIS 1000
Increment for encoder-based float value changes (in millis).
#define MIN_PROGRAM_SEQ_LENGTH 1
Minimum number of sequences in a program.
#define MAX_PROGRAM_SEQ_LENGTH 10
Maximum number of sequences in a program.
#define MAX_PROGRAMS 10
Maximum number of programs that can be stored.
#define MAX_SETTINGS 8
Maximum number of settings.
Enumerations
enum ui_menupoint_t {
NO_MENUPOINT , SETTINGS , SETTINGS_OVERVIEW , SETPOINT ,
PROGRAMS , PROGRAMS_OVERVIEW , PROGRAM_DETAILED , CREATE_PROGRAM ,
CREATE_PROGRAM_DETAILED
}
Menu state enumeration for UI state machine.
Functions
void initUI (Ui_HandleTypeDef_t *ui, Event_Queue_HandleTypeDef_t *queue, LCD1602_RGB_HandleTypeDef_t *hlcd)
Initialize the UI module.
HAL_StatusTypeDef ui_update (Ui_HandleTypeDef_t *ui)
Update UI state machine.
event_type_t ui_get_events (Ui_HandleTypeDef_t *ui)
Get next event from UI event queue.
Detailed Description
User interface module for menu-driven LCD control.
Author
Dennis Rathgeb
Date
Apr 20, 2024
Implements a state machine-based menu system for the kiln controller. Uses a 16x2 LCD display and rotary encoder with buttons for navigation.
Menu Structure
PROGRAMS <-> SETPOINT <-> SETTINGS
    |                        |
PROGRAMS_OVERVIEW      SETTINGS_OVERVIEW
    |
PROGRAM_DETAILED / CREATE_PROGRAM
                          |
                  CREATE_PROGRAM_DETAILED
Navigation
BUT1/ENC_DOWN: Navigate left/down
BUT2/ENC_UP: Navigate right/up
BUT3: Navigate back
ENC_BUT: Enter/select
Programs
Programs define firing profiles with gradient (degrees C/hour) and target temperature sequences for ceramic firing.
Definition in file ui.h.
Macro Definition Documentation
BUTTON_INC
#define BUTTON_INC 5
Increment step for button-based value changes.
Definition at line 63 of file ui.h.
Referenced by ui_update_create_program_detailed().
BUTTON_INC_FLOAT_MILLIS
#define BUTTON_INC_FLOAT_MILLIS 100
Increment for button-based float value changes (in millis, divide by 1000).
Definition at line 69 of file ui.h.
Referenced by ui_update_settings_overview().
ENC_INC
#define ENC_INC 20
Increment step for encoder-based value changes.
Definition at line 66 of file ui.h.
Referenced by ui_update_create_program_detailed().
ENC_INC_FLOAT_MILLIS
#define ENC_INC_FLOAT_MILLIS 1000
Increment for encoder-based float value changes (in millis).
Definition at line 72 of file ui.h.
Referenced by ui_update_settings_overview().
MAX_GRADIENT
#define MAX_GRADIENT 650
Maximum allowed gradient in degrees C per hour (both positive and negative).
Definition at line 54 of file ui.h.
Referenced by ui_fill_program_values().
MAX_PROGRAM_SEQ_LENGTH
#define MAX_PROGRAM_SEQ_LENGTH 10
Maximum number of sequences in a program.
Definition at line 78 of file ui.h.
Referenced by ui_fill_program_values().
MAX_PROGRAMS
#define MAX_PROGRAMS 10
Maximum number of programs that can be stored.
Definition at line 81 of file ui.h.
MAX_SETTING
#define MAX_SETTING 20
Maximum allowed setting value (both positive and negative).
Definition at line 60 of file ui.h.
Referenced by ui_update_settings_overview().
MAX_SETTING_TIME
#define MAX_SETTING_TIME 20
Maximum allowed time setting value.
Definition at line 57 of file ui.h.
MAX_SETTINGS
#define MAX_SETTINGS 8
Maximum number of settings.
Definition at line 84 of file ui.h.
MAX_TEMPERATURE
#define MAX_TEMPERATURE 1300
Maximum allowed temperature in degrees C.
Definition at line 51 of file ui.h.
Referenced by ui_fill_program_values().
MIN_PROGRAM_SEQ_LENGTH
#define MIN_PROGRAM_SEQ_LENGTH 1
Minimum number of sequences in a program.
Definition at line 75 of file ui.h.
Referenced by ui_fill_program_values().
UI_ENABLE_LOG
#define UI_ENABLE_LOG
Enable debug logging for UI module.
Definition at line 45 of file ui.h.
UI_LCD_CHAR_SIZE
#define UI_LCD_CHAR_SIZE 17
LCD character buffer size (16 chars + null).
Definition at line 48 of file ui.h.
Referenced by ui_print_lcd(), ui_update_create_program_detailed(), ui_update_program_detailed(), and ui_update_settings_overview().
Enumeration Type Documentation
ui_menupoint_t
enum ui_menupoint_t
Menu state enumeration for UI state machine.
Defines all possible menu points/screens in the UI.
Enumerator
NO_MENUPOINT
Initial/invalid state
SETTINGS
Main settings menu
SETTINGS_OVERVIEW
Settings list view
SETPOINT
Setpoint selection menu
PROGRAMS
Main programs menu
PROGRAMS_OVERVIEW
Programs list view
PROGRAM_DETAILED
View program details
CREATE_PROGRAM
Create new program entry point
CREATE_PROGRAM_DETAILED
Create program - enter values
Definition at line 91 of file ui.h.
Function Documentation
initUI()
void initUI (Ui_HandleTypeDef_t * ui, Event_Queue_HandleTypeDef_t * queue, LCD1602_RGB_HandleTypeDef_t * hlcd)
Initialize the UI module.
Parameters
[out] ui Pointer to UI handle to initialize
[in] queue Pointer to event queue for input events
[in] hlcd Pointer to LCD handle for display output
Initializes UI state machine, loads default programs and settings, and configures custom LCD characters for degree symbol.
Parameters
[out] ui Pointer to UI handle to initialize
[in] queue Pointer to event queue for input events
[in] hlcd Pointer to LCD handle for display output
Sets up initial state, loads default programs and settings, and creates custom LCD characters for temperature display.
Definition at line 84 of file ui.c.
References ui_programs_t::cur_index, ui_settings_t::cur_index, degree, degree_slash, hlcd, Ui_HandleTypeDef_t::hlcd, interval_gradient, interval_setpoint, kd_gradient, kd_setpoint, ki_gradient, ki_setpoint, kp_gradient, kp_setpoint, Ui_HandleTypeDef_t::last_state, lcd1602_customSymbol(), ui_programs_t::length, ui_settings_t::length, NO_MENUPOINT, p1, p2, p3, ui_programs_t::program_list, PROGRAMS, Ui_HandleTypeDef_t::programs, Ui_HandleTypeDef_t::queue, ui_settings_t::setting_list, Ui_HandleTypeDef_t::settings, and Ui_HandleTypeDef_t::state.
Referenced by main().
ui_get_events()
event_type_t ui_get_events (Ui_HandleTypeDef_t * ui)
Get next event from UI event queue.
Parameters
[in] ui Pointer to UI handle
Returns
Next event from queue, or NO_EVENT if queue is empty
Definition at line 780 of file ui.c.
References event_dequeue(), event_isEmpty(), NO_EVENT, and Ui_HandleTypeDef_t::queue.
Referenced by ui_update().
ui_update()
HAL_StatusTypeDef ui_update (Ui_HandleTypeDef_t * ui)
Update UI state machine.
Parameters
[in,out] ui Pointer to UI handle
Returns
HAL_OK on success, HAL_ERROR on invalid event
Main UI update function. Should be called in main loop. Processes events from the event queue and updates display accordingly.
Update UI state machine.
Parameters
[in,out] ui Pointer to UI handle
Returns
HAL_OK on success, HAL_ERROR on invalid event in sub-handler
Called from main loop. Processes events and dispatches to appropriate state handler based on current menu state. Only updates display if state changed or event occurred.
Definition at line 798 of file ui.c.
References CREATE_PROGRAM, CREATE_PROGRAM_DETAILED, Ui_HandleTypeDef_t::last_state, NO_EVENT, PROGRAM_DETAILED, PROGRAMS, PROGRAMS_OVERVIEW, SETPOINT, SETTINGS, SETTINGS_OVERVIEW, Ui_HandleTypeDef_t::state, ui_get_events(), ui_update_create_program(), ui_update_create_program_detailed(), ui_update_program_detailed(), ui_update_programs(), ui_update_programs_overview(), ui_update_setpoint(), ui_update_settings(), and ui_update_settings_overview().