PotteryOven Kiln Controller: Core/Src/ui.c File Reference
ui.c File Reference
Implementation of menu-driven user interface.
#include "ui.h"
Functions
void initUI (Ui_HandleTypeDef_t *ui, Event_Queue_HandleTypeDef_t *queue, LCD1602_RGB_HandleTypeDef_t *hlcd)
Initialize the UI module.
void ui_print_lcd (Ui_HandleTypeDef_t *ui, char top[17], char bottom[17])
Display two rows of text on the LCD.
void ui_print_lcd_program_symb (Ui_HandleTypeDef_t *ui)
Print custom degree symbols on LCD for program view.
static void ui_fill_lcd_buf_program (ui_program_t *program, uint8_t program_index, char text_buf_top[][17], char text_buf_bottom[][17], uint8_t length)
Fill LCD buffers with program step data.
static void ui_fill_program_values (ui_program_t *program)
Update program values from temporary input variables.
static HAL_StatusTypeDef ui_update_create_program_detailed (Ui_HandleTypeDef_t *ui, event_type_t event)
Handle CREATE_PROGRAM_DETAILED menu state.
static HAL_StatusTypeDef ui_update_create_program (Ui_HandleTypeDef_t *ui, event_type_t event)
Handle CREATE_PROGRAM menu state.
static HAL_StatusTypeDef ui_update_program_detailed (Ui_HandleTypeDef_t *ui, event_type_t event)
Handle PROGRAM_DETAILED menu state.
static HAL_StatusTypeDef ui_update_programs_overview (Ui_HandleTypeDef_t *ui, event_type_t event)
Handle PROGRAMS_OVERVIEW menu state.
static HAL_StatusTypeDef ui_update_settings_overview (Ui_HandleTypeDef_t *ui, event_type_t event)
Handle SETTINGS_OVERVIEW menu state.
static HAL_StatusTypeDef ui_update_programs (Ui_HandleTypeDef_t *ui, event_type_t event)
Handle PROGRAMS main menu state.
static HAL_StatusTypeDef ui_update_setpoint (Ui_HandleTypeDef_t *ui, event_type_t event)
Handle SETPOINT menu state.
static HAL_StatusTypeDef ui_update_settings (Ui_HandleTypeDef_t *ui, event_type_t event)
Handle SETTINGS main menu state.
event_type_t ui_get_events (Ui_HandleTypeDef_t *ui)
Get next event from UI event queue.
HAL_StatusTypeDef ui_update (Ui_HandleTypeDef_t *ui)
Main UI state machine update function.
Variables
static ui_program_t p1 = {3, {288, 300, 150}, {0, 1, 1}, {200, 80, 120}}
static ui_program_t p2 = {5, {80, 60, 150, 300, 80}, {0, 1, 0, 0, 1}, {15, 80, 120, 300, 600}}
static ui_program_t p3 = {2, {300, 150}, {0, 0}, {300, 80}}
ui_setting_t kp_gradient = {" KP GRADIENT: ", 8.2}
ui_setting_t ki_gradient = {" KI GRADIENT: ", 20}
ui_setting_t kd_gradient = {" KD GRADIENT: ", 42.23}
ui_setting_t interval_gradient = {" INT GRADIENT: ", 100}
ui_setting_t kp_setpoint = {" KP SETPOINT: ", 6}
ui_setting_t ki_setpoint = {" KI SETPOINT: ", 0.2}
ui_setting_t kd_setpoint = {" KD SETPOINT: ", -3.2}
ui_setting_t interval_setpoint = {" INT SETPOINT: ", 100}
static ui_program_t c_program = {1, {0}, {0}, {0}}
Temporary program for creating/modifying programs.
static uint16_t temp_counter = 0
Temporary counter for input values.
static uint16_t temp_counter_single = 0
Temporary counter for single-digit inputs.
static uint8_t temp_sign = 0
Temporary sign flag: 0=positive, 1=negative.
static uint8_t temp_bool = 0
Temporary boolean for edit mode toggle.
char empty_text_buf [17] = " \n"
Empty text buffer for clearing LCD line.
static uint8_t scroll_counter = 0
Scroll counter for navigating arrays in menus.
uint8_t degree_slash []
Custom character pattern for degree/slash symbol.
uint8_t degree []
Custom character pattern for degree symbol.
Detailed Description
Implementation of menu-driven user interface.
Author
Dennis Rathgeb
Date
Apr 20, 2024
Implements a state machine-based menu system for kiln control. Handles navigation, program creation, and settings adjustment via LCD display and rotary encoder input.
Definition in file ui.c.
Function Documentation
initUI()
void initUI (Ui_HandleTypeDef_t * ui, Event_Queue_HandleTypeDef_t * queue, LCD1602_RGB_HandleTypeDef_t * hlcd)
Initialize the UI module.
Parameters
[out] ui Pointer to UI handle to initialize
[in] queue Pointer to event queue for input events
[in] hlcd Pointer to LCD handle for display output
Sets up initial state, loads default programs and settings, and creates custom LCD characters for temperature display.
Definition at line 84 of file ui.c.
References ui_programs_t::cur_index, ui_settings_t::cur_index, degree, degree_slash, hlcd, Ui_HandleTypeDef_t::hlcd, interval_gradient, interval_setpoint, kd_gradient, kd_setpoint, ki_gradient, ki_setpoint, kp_gradient, kp_setpoint, Ui_HandleTypeDef_t::last_state, lcd1602_customSymbol(), ui_programs_t::length, ui_settings_t::length, NO_MENUPOINT, p1, p2, p3, ui_programs_t::program_list, PROGRAMS, Ui_HandleTypeDef_t::programs, Ui_HandleTypeDef_t::queue, ui_settings_t::setting_list, Ui_HandleTypeDef_t::settings, and Ui_HandleTypeDef_t::state.
Referenced by main().
ui_fill_lcd_buf_program()
void ui_fill_lcd_buf_program (ui_program_t * program, uint8_t program_index, char text_buf_top[][17], char text_buf_bottom[][17], uint8_t length) static
Fill LCD buffers with program step data.
Parameters
[in] program Pointer to program structure
[in] program_index Program number (0-based) for display
[out] text_buf_top Array of top row strings
[out] text_buf_bottom Array of bottom row strings
[in] length Number of steps to format
Formats program steps for display showing:
Top: "P#: step/total"
Bottom: "gradient -> temperature"
Definition at line 154 of file ui.c.
References ui_program_t::gradient, ui_program_t::gradient_negative, and ui_program_t::temperature.
Referenced by ui_update_create_program_detailed(), and ui_update_program_detailed().
ui_fill_program_values()
void ui_fill_program_values (ui_program_t * program) static
Update program values from temporary input variables.
Parameters
[in,out] program Pointer to program to update
Uses scroll_counter to determine which field to update:
0: program length
Odd: gradient value
Even: temperature value
Applies bounds checking for all values.
Definition at line 189 of file ui.c.
References ui_program_t::gradient, ui_program_t::gradient_negative, ui_program_t::length, MAX_GRADIENT, MAX_PROGRAM_SEQ_LENGTH, MAX_TEMPERATURE, MIN_PROGRAM_SEQ_LENGTH, scroll_counter, temp_counter, temp_counter_single, temp_sign, and ui_program_t::temperature.
Referenced by ui_update_create_program_detailed().
ui_get_events()
event_type_t ui_get_events (Ui_HandleTypeDef_t * ui)
Get next event from UI event queue.
Parameters
[in] ui Pointer to UI handle
Returns
Next event from queue, or NO_EVENT if queue is empty
Definition at line 780 of file ui.c.
References event_dequeue(), event_isEmpty(), NO_EVENT, and Ui_HandleTypeDef_t::queue.
Referenced by ui_update().
ui_print_lcd()
void ui_print_lcd (Ui_HandleTypeDef_t * ui, char top[17], char bottom[17])
Display two rows of text on the LCD.
Parameters
[in] ui Pointer to UI handle
[in] top Text for top row (16 chars max)
[in] bottom Text for bottom row (16 chars max)
Definition at line 118 of file ui.c.
References Ui_HandleTypeDef_t::hlcd, lcd1602_send_string(), lcd1602_setCursor(), and UI_LCD_CHAR_SIZE.
Referenced by ui_update_create_program(), ui_update_create_program_detailed(), ui_update_program_detailed(), ui_update_programs(), ui_update_programs_overview(), ui_update_setpoint(), ui_update_settings(), and ui_update_settings_overview().
ui_print_lcd_program_symb()
void ui_print_lcd_program_symb (Ui_HandleTypeDef_t * ui)
Print custom degree symbols on LCD for program view.
Parameters
[in] ui Pointer to UI handle
Displays degrees C/h symbol at position 4 and degrees C at position 13 on the bottom row for the program detailed view.
Definition at line 133 of file ui.c.
References Ui_HandleTypeDef_t::hlcd, lcd1602_setCursor(), and lcd1602_write_char().
Referenced by ui_update_create_program_detailed(), and ui_update_program_detailed().
ui_update()
HAL_StatusTypeDef ui_update (Ui_HandleTypeDef_t * ui)
Main UI state machine update function.
Update UI state machine.
Parameters
[in,out] ui Pointer to UI handle
Returns
HAL_OK on success, HAL_ERROR on invalid event in sub-handler
Called from main loop. Processes events and dispatches to appropriate state handler based on current menu state. Only updates display if state changed or event occurred.
Definition at line 798 of file ui.c.
References CREATE_PROGRAM, CREATE_PROGRAM_DETAILED, Ui_HandleTypeDef_t::last_state, NO_EVENT, PROGRAM_DETAILED, PROGRAMS, PROGRAMS_OVERVIEW, SETPOINT, SETTINGS, SETTINGS_OVERVIEW, Ui_HandleTypeDef_t::state, ui_get_events(), ui_update_create_program(), ui_update_create_program_detailed(), ui_update_program_detailed(), ui_update_programs(), ui_update_programs_overview(), ui_update_setpoint(), ui_update_settings(), and ui_update_settings_overview().
ui_update_create_program()
HAL_StatusTypeDef ui_update_create_program (Ui_HandleTypeDef_t * ui, event_type_t event) static
Handle CREATE_PROGRAM menu state.
Parameters
[in,out] ui Pointer to UI handle
[in] event Input event to process
Returns
HAL_OK on success, HAL_ERROR on invalid event
Entry point for creating a new program. Shows "CREATE NEW PROGRAM" message.
< Error level - error conditions
Definition at line 371 of file ui.c.
References BUT1, BUT2, BUT3, BUT4, CREATE_PROGRAM_DETAILED, ui_programs_t::cur_index, ENC_BUT, ENC_DOWN, ENC_UP, ui_programs_t::length, LOG_ERROR, logMsg(), NO_EVENT, PROGRAMS, Ui_HandleTypeDef_t::programs, PROGRAMS_OVERVIEW, Ui_HandleTypeDef_t::state, and ui_print_lcd().
Referenced by ui_update().
ui_update_create_program_detailed()
HAL_StatusTypeDef ui_update_create_program_detailed (Ui_HandleTypeDef_t * ui, event_type_t event) static
Handle CREATE_PROGRAM_DETAILED menu state.
Parameters
[in,out] ui Pointer to UI handle
[in] event Input event to process
Returns
HAL_OK on success, HAL_ERROR on invalid event
Allows entering program values step by step:
scroll_counter 0: program length
scroll_counter 1+: alternating gradient/temperature values
ENC_BUT advances to next field or saves program when complete
< Error level - error conditions
Definition at line 247 of file ui.c.
References BUT1, BUT2, BUT3, BUT4, BUTTON_INC, c_program, CREATE_PROGRAM, ui_programs_t::cur_index, empty_text_buf, ENC_BUT, ENC_DOWN, ENC_INC, ENC_UP, ui_programs_t::length, LOG_ERROR, logMsg(), NO_EVENT, ui_programs_t::program_list, Ui_HandleTypeDef_t::programs, PROGRAMS_OVERVIEW, scroll_counter, Ui_HandleTypeDef_t::state, temp_counter, temp_counter_single, temp_sign, ui_fill_lcd_buf_program(), ui_fill_program_values(), UI_LCD_CHAR_SIZE, ui_print_lcd(), and ui_print_lcd_program_symb().
Referenced by ui_update().
ui_update_program_detailed()
HAL_StatusTypeDef ui_update_program_detailed (Ui_HandleTypeDef_t * ui, event_type_t event) static
Handle PROGRAM_DETAILED menu state.
Parameters
[in,out] ui Pointer to UI handle
[in] event Input event to process
Returns
HAL_OK on success, HAL_ERROR on invalid event
Displays detailed view of selected program with gradient and temperature for each step. Scroll to navigate between steps.
< Error level - error conditions
Definition at line 421 of file ui.c.
References BUT1, BUT2, BUT3, BUT4, ui_programs_t::cur_index, ENC_BUT, ENC_DOWN, ENC_UP, ui_program_t::length, ui_programs_t::length, LOG_ERROR, logMsg(), NO_EVENT, ui_programs_t::program_list, Ui_HandleTypeDef_t::programs, PROGRAMS_OVERVIEW, scroll_counter, Ui_HandleTypeDef_t::state, ui_fill_lcd_buf_program(), UI_LCD_CHAR_SIZE, ui_print_lcd(), and ui_print_lcd_program_symb().
Referenced by ui_update().
ui_update_programs()
HAL_StatusTypeDef ui_update_programs (Ui_HandleTypeDef_t * ui, event_type_t event) static
Handle PROGRAMS main menu state.
Parameters
[in,out] ui Pointer to UI handle
[in] event Input event to process
Returns
HAL_OK on success, HAL_ERROR on invalid event
Main programs menu. Navigate left/right to SETTINGS/SETPOINT, ENC_BUT to enter programs overview.
< Error level - error conditions
Definition at line 653 of file ui.c.
References BUT1, BUT2, BUT3, BUT4, empty_text_buf, ENC_BUT, ENC_DOWN, ENC_UP, LOG_ERROR, logMsg(), NO_EVENT, PROGRAMS_OVERVIEW, SETPOINT, SETTINGS, Ui_HandleTypeDef_t::state, and ui_print_lcd().
Referenced by ui_update().
ui_update_programs_overview()
HAL_StatusTypeDef ui_update_programs_overview (Ui_HandleTypeDef_t * ui, event_type_t event) static
Handle PROGRAMS_OVERVIEW menu state.
Parameters
[in,out] ui Pointer to UI handle
[in] event Input event to process
Returns
HAL_OK on success, HAL_ERROR on invalid event
Shows list of available programs. Navigate to select, ENC_BUT to view details, scrolling past end goes to CREATE_PROGRAM.
< Error level - error conditions
Definition at line 482 of file ui.c.
References BUT1, BUT2, BUT3, BUT4, CREATE_PROGRAM, ui_programs_t::cur_index, empty_text_buf, ENC_BUT, ENC_DOWN, ENC_UP, ui_programs_t::length, LOG_ERROR, logMsg(), NO_EVENT, PROGRAM_DETAILED, PROGRAMS, Ui_HandleTypeDef_t::programs, Ui_HandleTypeDef_t::state, and ui_print_lcd().
Referenced by ui_update().
ui_update_setpoint()
HAL_StatusTypeDef ui_update_setpoint (Ui_HandleTypeDef_t * ui, event_type_t event) static
Handle SETPOINT menu state.
Parameters
[in,out] ui Pointer to UI handle
[in] event Input event to process
Returns
HAL_OK on success, HAL_ERROR on invalid event
Setpoint selection menu (functionality TODO).
< Error level - error conditions
Definition at line 696 of file ui.c.
References BUT1, BUT2, BUT3, BUT4, empty_text_buf, ENC_BUT, ENC_DOWN, ENC_UP, LOG_ERROR, logMsg(), NO_EVENT, PROGRAMS, SETTINGS, Ui_HandleTypeDef_t::state, and ui_print_lcd().
Referenced by ui_update().
ui_update_settings()
HAL_StatusTypeDef ui_update_settings (Ui_HandleTypeDef_t * ui, event_type_t event) static
Handle SETTINGS main menu state.
Parameters
[in,out] ui Pointer to UI handle
[in] event Input event to process
Returns
HAL_OK on success, HAL_ERROR on invalid event
Main settings menu. Navigate left/right to SETPOINT/PROGRAMS, ENC_BUT to enter settings overview.
< Error level - error conditions
Definition at line 740 of file ui.c.
References BUT1, BUT2, BUT3, BUT4, empty_text_buf, ENC_BUT, ENC_DOWN, ENC_UP, LOG_ERROR, logMsg(), NO_EVENT, PROGRAMS, SETPOINT, SETTINGS_OVERVIEW, Ui_HandleTypeDef_t::state, and ui_print_lcd().
Referenced by ui_update().
ui_update_settings_overview()
HAL_StatusTypeDef ui_update_settings_overview (Ui_HandleTypeDef_t * ui, event_type_t event) static
Handle SETTINGS_OVERVIEW menu state.
Parameters
[in,out] ui Pointer to UI handle
[in] event Input event to process
Returns
HAL_OK on success, HAL_ERROR on invalid event
Shows list of settings. ENC_BUT toggles edit mode for adjusting values.
< Error level - error conditions
Definition at line 559 of file ui.c.
References BUT1, BUT2, BUT3, BUT4, BUTTON_INC_FLOAT_MILLIS, ui_settings_t::cur_index, ENC_BUT, ENC_DOWN, ENC_INC_FLOAT_MILLIS, ENC_UP, ui_settings_t::length, LOG_ERROR, logMsg(), MAX_SETTING, ui_setting_t::name, NO_EVENT, ui_settings_t::setting_list, SETTINGS, Ui_HandleTypeDef_t::settings, Ui_HandleTypeDef_t::state, temp_bool, UI_LCD_CHAR_SIZE, ui_print_lcd(), and ui_setting_t::value.
Referenced by ui_update().
Variable Documentation
c_program
ui_program_t c_program = {1, {0}, {0}, {0}} static
Temporary program for creating/modifying programs.
Definition at line 31 of file ui.c.
Referenced by ui_update_create_program_detailed().
degree
uint8_t degree[]
Initial value:
               = {
    0b00110,
    0b01001,
    0b01001,
    0b00110,
    0b00000,
    0b00000,
    0b00000,
    0b00000
}
Custom character pattern for degree symbol.
Definition at line 64 of file ui.c.
Referenced by initUI().
degree_slash
uint8_t degree_slash[]
Initial value:
                     = {
    0b01000,
    0b10101,
    0b01010,
    0b00100,
    0b01000,
    0b10100,
    0b00111,
    0b00101
}
Custom character pattern for degree/slash symbol.
Definition at line 52 of file ui.c.
Referenced by initUI().
empty_text_buf
char empty_text_buf[17] = " \n"
Empty text buffer for clearing LCD line.
Definition at line 46 of file ui.c.
Referenced by ui_update_create_program_detailed(), ui_update_programs(), ui_update_programs_overview(), ui_update_setpoint(), and ui_update_settings().
interval_gradient
ui_setting_t interval_gradient = {" INT GRADIENT: ", 100}
Definition at line 23 of file ui.c.
Referenced by initUI().
interval_setpoint
ui_setting_t interval_setpoint = {" INT SETPOINT: ", 100}
Definition at line 28 of file ui.c.
Referenced by initUI().
kd_gradient
ui_setting_t kd_gradient = {" KD GRADIENT: ", 42.23}
Definition at line 22 of file ui.c.
Referenced by initUI().
kd_setpoint
ui_setting_t kd_setpoint = {" KD SETPOINT: ", -3.2}
Definition at line 27 of file ui.c.
Referenced by initUI().
ki_gradient
ui_setting_t ki_gradient = {" KI GRADIENT: ", 20}
Definition at line 21 of file ui.c.
Referenced by initUI().
ki_setpoint
ui_setting_t ki_setpoint = {" KI SETPOINT: ", 0.2}
Definition at line 26 of file ui.c.
Referenced by initUI().
kp_gradient
ui_setting_t kp_gradient = {" KP GRADIENT: ", 8.2}
Definition at line 20 of file ui.c.
Referenced by initUI().
kp_setpoint
ui_setting_t kp_setpoint = {" KP SETPOINT: ", 6}
Definition at line 25 of file ui.c.
Referenced by initUI().
p1
ui_program_t p1 = {3, {288, 300, 150}, {0, 1, 1}, {200, 80, 120}} static
Definition at line 15 of file ui.c.
Referenced by initUI().
p2
ui_program_t p2 = {5, {80, 60, 150, 300, 80}, {0, 1, 0, 0, 1}, {15, 80, 120, 300, 600}} static
Definition at line 16 of file ui.c.
Referenced by initUI().
p3
ui_program_t p3 = {2, {300, 150}, {0, 0}, {300, 80}} static
Definition at line 17 of file ui.c.
Referenced by initUI().
scroll_counter
uint8_t scroll_counter = 0 static
Scroll counter for navigating arrays in menus.
Definition at line 49 of file ui.c.
Referenced by ui_fill_program_values(), ui_update_create_program_detailed(), and ui_update_program_detailed().
temp_bool
uint8_t temp_bool = 0 static
Temporary boolean for edit mode toggle.
Definition at line 43 of file ui.c.
Referenced by ui_update_settings_overview().
temp_counter
uint16_t temp_counter = 0 static
Temporary counter for input values.
Definition at line 34 of file ui.c.
Referenced by ui_fill_program_values(), and ui_update_create_program_detailed().
temp_counter_single
uint16_t temp_counter_single = 0 static
Temporary counter for single-digit inputs.
Definition at line 37 of file ui.c.
Referenced by ui_fill_program_values(), and ui_update_create_program_detailed().
temp_sign
uint8_t temp_sign = 0 static
Temporary sign flag: 0=positive, 1=negative.
Definition at line 40 of file ui.c.
Referenced by max31855_get_temp_f32(), ui_fill_program_values(), and ui_update_create_program_detailed().